Fixes lint issues
kubearmor/KubeArmor pull request #1024
Opened 2022-12-19 15:16 UTC by Vishal-Chdhry

Signed-off-by: Vishal Choudhary <contactvishaltech@gmail.com>

**Purpose of PR?**:
Fixes lining issues generated while running `make golint`
Fixes #1018 

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #1018 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2022-12-22 18:02 UTC, vishal-chdhry commented
@daemon1024 @nyrahul Made some changes, you might want to take a look.
And I am not entirely aware of what every package does so i couldn't write a descriptive comment about it.

2023-01-02 03:20 UTC, nyrahul commented
I am mostly good to merge these changes. Can you please fix the merge conflicts?

2023-01-02 14:01 UTC, Vishal-Chdhry commented
@nyrahul done!

2023-01-04 11:59 UTC, daemon1024 requested changes
Hey @Vishal-Chdhry, I have added some suggestions and expanded on the comments.

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/common/common.go
> +// Package common declaration
```suggestion
// Package common contains utility functions which are commonly used across packages and modules
```

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/core/containerdHandler.go
> +// Package core declaration
```suggestion
// Package core is responsible for initiating and maintaining interactions between external entities like K8s,CRIs and internal KubeArmor entities like eBPF Monitor and Log Feeders
```

Let's move this comment declaration to `core/kubeArmor.go`

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/enforcer/appArmorEnforcer.go
> +// Package enforcer declaration
```suggestion
// Package enforcer is responsible for setting up and handling policy updates for supported enforcers including AppArmor, SELinux and BPFLSM
```

Let's move this comment to `enforcer/runtimeEnforcer.go`

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/enforcer/SELinuxEnforcer.go
> +// Package enforcer declaration
```suggestion
```

duplicate

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/feeder/feeder.go
> +// Package feeder declaration
```suggestion
// Package feeder is responsible for sanitizing and pushing telemetry data to connected clients 
```

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/kvmAgent/kvmAgent.go
> +// Package kvmagent declaration
```suggestion
// Package kvmagent contains utilities to connect to kvmservice to establish support on bare-metal env
```

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/log/logger.go
> +// Package log declaration
```suggestion
// Package log contains log util wrappers for enhanced pretty logging
```

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/main.go
> +// Package main declaration
```suggestion
// Package main is the entrypoint to initializing the armor
```

2023-01-04 11:59 UTC, daemon1024 commented on KubeArmor/policy/policy.go
> +// Package policy declaration
```suggestion
// Package policy handles policy updates over gRPC in non-k8s environment
```

2023-01-04 12:07 UTC, daemon1024 approved these changes

2023-01-10 03:18 UTC, nyrahul approved these changes
LGTM

2023-01-10 03:56 UTC, merged