docs: Provides documentation on Kubearmor container visibility
kubearmor/KubeArmor pull request #1028
Opened 2022-12-27 12:29 UTC by TheRealSibasishBehera

**Resolves Issue #481**:

Provides documentation for kubearmor container visibility

This PR provides docs for feature mentioned in issue #126 and #398

2023-01-02 03:05 UTC, nyrahul submitted a review, later dismissed
Thanks for looking into this. Please find my comments.

2023-01-02 03:05 UTC, nyrahul commented on getting-started/kubearmor_visibility.md
> +
We can explain what kind of visibility information would be available. For e.g.,
1. Process
2. Files
3. Networks

Sample screenshots using [collapsible sections](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab).

2023-01-02 03:05 UTC, nyrahul commented on getting-started/kubearmor_visibility.md
> + The following  example would require a K8s cluster , please follow [this](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md#prerequisites) to setup one if you dont
Best to use [grammarly](https://app.grammarly.com/) to fix the basic grammatical issues.

2023-01-02 03:05 UTC, nyrahul commented on getting-started/kubearmor_visibility.md
> +  ```
We do not have to repeat the installation steps here. We can point to the getting started guide. The problem is if there are any changes to the getting started guide then multiple pages have to be updated.

2023-01-02 03:05 UTC, nyrahul commented on getting-started/kubearmor_visibility.md
> +### Example : multiubuntu
I would rather suggest using wordpress-mysql as an example since it is more realistic.

2023-01-04 06:33 UTC, TheRealSibasishBehera commented
@nyrahul i worked on the issues , 
can you please review them

2023-01-25 09:20 UTC, Ankurk99 requested changes
Why don't we include host visibility doc in the same page? Wdyt?
I also have some suggestions, ptal at inline comments

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +* In the terminal running `karmor log`, the policy violation along with container visibility is shown, in this case for example
the command is updated to `karmor logs` now, please update that

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +* The logs can also be generated in JSON format using `karmor log --json `
`karmor logs --json`

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +  <summary>Know More On Visibillity</summary>
> Know More On Visibillity
<summary>Available visibility options:</summary>

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +* To install karmor CLI tool in the cluster follow [here](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md#1-download-and-install-karmor-cli-tool)
> * To install karmor CLI tool in the cluster follow [here](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md#1-download-and-install-karmor-cli-tool)

* karmor CLI tool: [Download and install karmor-cli](https://github.com/kubearmor/KubeArmor/blob/main/getting-started/deployment_guide.md#1-download-and-install-karmor-cli-tool)

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +  $ karmor log
karmor logs

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +  * Container visibility is enabled by default, in this case, we can check it using `kubectl describe` and greping `kubearmor-visibility `
>   * Container visibility is enabled by default, in this case, we can check it using `kubectl describe` and greping `kubearmor-visibility `

  * Container visibility is enabled by default. We can check it using `kubectl describe` and grep `kubearmor-visibility `

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +* In another terminal, simulate a policy violation, in this case trying `sleep` inside a pod
> * In another terminal, simulate a policy violation, in this case trying `sleep` inside a pod

* In another terminal, simulate a policy violation. Try `sleep` inside a pod

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +  $ POD_NAME=$(kubectl get pods -n wordpress-mysql -l app=wordpress -o jsonpath='{.items[0].metadata.name}') && kubectl describe -n wordpress-mysql pod $POD_NAME | grep kubearmor-visibility
Can we remove the $ sign so that the user can directly copy-paste the entire command?

2023-01-25 09:20 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +  * Alternate : (For pre-existing workloads) Enable visibility using `kubectl annotate`, currently KubeArmor supports `process`, `file`, `network`, `capabilities`
>   * Alternate : (For pre-existing workloads) Enable visibility using `kubectl annotate`, currently KubeArmor supports `process`, `file`, `network`, `capabilities`

  * **For pre-existing workloads :** Enable visibility using `kubectl annotate`. Currently KubeArmor supports `process`, `file`, `network` and `capabilities`.

2023-01-25 11:56 UTC, TheRealSibasishBehera commented
> Why don't we include host visibility doc in the same page? Wdyt? I also have some suggestions, ptal at inline comments

Thanks for reviewing 

I think we can do that 

If i am right host visibility is not enabled by default and we can use ` kubectl annotate node` for that

Are the stats related to host visibility also fetched  with `karmor logs` ?

2023-01-25 12:16 UTC, Ankurk99 commented
> > Why don't we include host visibility doc in the same page? Wdyt? I also have some suggestions, ptal at inline comments
> 
> Thanks for reviewing , i will fix the issues
> 
> I think we can include host visibility doc
> 
> If i am right host visibility is not enabled by default and we can use ` kubectl annotate node` for that

Correct

> Are the stats related to host visibility also fetched with `karmor logs` ?

Yes, karmor logs has that.

2023-01-30 05:20 UTC, Ankurk99 commented
Awesome! Congratulations on your first PR!

2023-01-30 05:23 UTC, Ankurk99 approved these changes

2023-01-30 05:24 UTC, merged