feat(monitor): mount/unmount syscall support
kubearmor/KubeArmor pull request #1043
Opened 2023-01-11 05:39 UTC by rksharma95

**Purpose of PR?**:
This PR adds support for mount and unmount syscalls. after merging the KubeArmor will be able to trace all events of mount/unmount system call. It also makes both the syscalls auditable, so both can be audit at syscall level using an audit policy.
```
syscalls:
  matchSyscalls:
  - syscall:
    - mount
    - umount2

```
Fixes #1011 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Fixes #1011
- [x] New feature (non-breaking change which adds functionality)
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has integration tests

2023-01-16 16:57 UTC, nyrahul commented
Ensure that we have a document explaining:
1. Sample mount/umount telemetry events
2. output of `karmor summary` with corresponding syscalls
3. Ginkgo tests.

2023-01-23 11:03 UTC, rksharma95 commented
In KubeArmor, default apparmor profile for k8s workload denies mount/unmount.
@nyrahul  if we want to add automated test for mount/unmount syscall, the possible ways are:
- edit native apparmor profile under `/etc/apparmor.d` after applying the audit policy.
- don't modify the profile and just check for the expected alert from `DefaultPosture` with `Action: Block`. 

for ref., here i'm pasting the telemetry generated during the manual testing.

i'm using the manually edited custom apparmor profile for the testing pod.
<details>
  <summary>apparmor profile</summary>
  
```
## == Managed by KubeArmor == ##
#include <tunables/global>

## == Dispatcher profile START == ##
profile kubearmor-test-mount-ubuntu-1-deployment-ubuntu-1-container flags=(attach_disconnected,mediate_deleted) {
        ## == PRE START == ##
        #include <abstractions/base>
                                file,
                                network,
                                capability,
                                mount,
                                umount,
        ## == PRE END == ##

        ## == File/Dir START == ##
  ## == File/Dir END == ##
        ## == DISPATCHER START == ##
        ## == DISPATCHER END == ##

  ## == Network START == ##
  ## == Network END == ##

  ## == Capabilities START == ##
  ## == Capabilities END == ##

        ## == Native Policy START == ##

        ## == Native Policy END == ##


        ## == POST START == ##
        /lib/x86_64-linux-gnu/{*,**} rm,

        deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
        deny @{PROC}/sysrq-trigger rwklx,
        deny @{PROC}/mem rwklx,
        deny @{PROC}/kmem rwklx,
        deny @{PROC}/kcore rwklx,

        # deny mount,

        deny /sys/[^f]*/** wklx,
        deny /sys/f[^s]*/** wklx,
        deny /sys/fs/[^c]*/** wklx,
        deny /sys/fs/c[^g]*/** wklx,
        deny /sys/fs/cg[^r]*/** wklx,
        deny /sys/firmware/efi/efivars/** rwklx,
        deny /sys/kernel/security/** rwklx,

        ## == POST END == ##
}
## == Dispatcher profile END == ##

## == FromSource per binary profiles START == ##
## == FromSource per binary profiles END == ##

## == Templates section START == ##
```
  
</details>

audit policy for mount and umount syscall

<details>
  <summary>policy.yaml</summary>
  
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: audit-all-mount-unmount
  namespace: test-mount
spec:
  severity: 3
  selector:
    matchLabels:
      container: ubuntu-1
  syscalls:
    matchSyscalls:
    - syscall:
      - mount
      - umount2
  action: Audit
```  
</details>

telemetry alerts

```
$ root@ubuntu-1-deployment-868d6fd7bf-4qqkh:/# mount --bind /home /mnt/test
```

<details>
  <summary>Alert</summary>

```yaml
== Alert / 2023-01-23 10:30:41.707721 ==
ClusterName: default
HostName: hp
NamespaceName: test-mount
PodName: ubuntu-1-deployment-868d6fd7bf-4qqkh
Labels: container=ubuntu-1
ContainerName: ubuntu-1-container
ContainerID: ac3ab371caac7afa227c1229812c47514aa96e17237049d866515386c84c928c
ContainerImage: docker.io/kubearmor/ubuntu-w-utils:0.1@sha256:b4693b003ed1fbf7f5ef2c8b9b3f96fd853c30e1b39549cf98bd772fbd99e260
Type: MatchedPolicy
PolicyName: audit-all-mount-unmount
Severity: 3
Source: /bin/mount --bind /home /mnt/test
Operation: Syscall
Data: syscall=SYS_MOUNT source=/home target=/mnt/test filesystem=none mountflag=0 data=
Result: Passed
HostPID: 62346
HostPPID: 60252
PID: 142
PPID: 125
ParentProcessName: /bin/bash
ProcessName: /bin/mount
```
  
</details>

```
root@ubuntu-1-deployment-868d6fd7bf-4qqkh:/# umount /mnt/test
```

<details>
  <summary>Alert</summary>

```yaml
== Alert / 2023-01-23 10:31:00.718011 ==
ClusterName: default
HostName: hp
NamespaceName: test-mount
PodName: ubuntu-1-deployment-868d6fd7bf-4qqkh
Labels: container=ubuntu-1
ContainerName: ubuntu-1-container
ContainerID: ac3ab371caac7afa227c1229812c47514aa96e17237049d866515386c84c928c
ContainerImage: docker.io/kubearmor/ubuntu-w-utils:0.1@sha256:b4693b003ed1fbf7f5ef2c8b9b3f96fd853c30e1b39549cf98bd772fbd99e260
Type: MatchedPolicy
PolicyName: audit-all-mount-unmount
Severity: 3
Source: /bin/umount /mnt/test
Operation: Syscall
Data: syscall=SYS_UMOUNT2 target=/mnt/test flag=0
Result: Passed
HostPID: 62369
HostPPID: 60252
PID: 143
PPID: 125
ParentProcessName: /bin/bash
ProcessName: /bin/umount
```
  
</details>

2023-02-07 07:46 UTC, daemon1024 approved these changes
LGTM! 👌🏽

2023-02-07 07:49 UTC, daemon1024 commented
Can you please resolve the conflicts?

2023-02-07 08:55 UTC, achrefbensaad requested changes

2023-02-07 08:55 UTC, achrefbensaad commented on KubeArmor/monitor/logUpdate.go
> +				log.Data = "syscall=" + getSyscallName(int32(msg.ContextSys.EventID)) + " source=" + source + " target=" + target + " filesystem=" + fstype + " mountflag=" + strconv.Itoa(flags) + " data=" + data
Will the data field always has a value or it will be always empty ? if the latter please remove it.

2023-02-07 08:55 UTC, achrefbensaad commented on KubeArmor/BPF/system_monitor.c
> +    bpf_printk("mount syscall called\n");
please remove all bpf_printk from the code.

2023-02-07 09:31 UTC, rksharma95 commented on KubeArmor/monitor/logUpdate.go
> +				log.Data = "syscall=" + getSyscallName(int32(msg.ContextSys.EventID)) + " source=" + source + " target=" + target + " filesystem=" + fstype + " mountflag=" + strconv.Itoa(flags) + " data=" + data
it will not be always empty...yes in some cases it will be empty.

2023-02-07 09:45 UTC, rksharma95 commented on KubeArmor/BPF/system_monitor.c
> +    bpf_printk("mount syscall called\n");
removed :+1:

2023-02-07 09:46 UTC, achrefbensaad approved these changes

2023-02-07 11:27 UTC, merged