fix(logs): Fix missing startup events & fix memory leak.
kubearmor/KubeArmor pull request #1068
Opened 2023-01-25 13:38 UTC by achrefbensaad

**Purpose of PR?**:

1- capture startup events by replaying events
2- fix memory leak in execLogMap

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-01-27 13:32 UTC, vishnusomank approved these changes
LGTM!

@achrefbensaad  Please have a look at the lint issue https://github.com/kubearmor/KubeArmor/pull/1068/files#diff-d7cb05ca55c8575bb5f5e1035e622b7e27e0b548dba93e64e3b3c80bf0bd6e38R48

2023-01-27 18:23 UTC, nyrahul commented on KubeArmor/monitor/systemMonitor.go
> +type ContextReplay struct {
Please fix the lint.

2023-01-27 18:23 UTC, nyrahul commented on KubeArmor/monitor/processTree.go
> +							delete(mon.execLogMap, pid)
Can we wrap this into a func and call from both places?

2023-01-27 18:23 UTC, nyrahul commented on KubeArmor/monitor/systemMonitor.go
> +				continue
Is it ok to continue here? If yes, better to put a few ms sleep here so that this can yield to other routines.

2023-01-27 18:23 UTC, nyrahul commented on KubeArmor/monitor/systemMonitor.go
> +				time.Sleep(1 * time.Second)
We need an online code review for this, early next week.

2023-01-30 06:44 UTC, nyrahul requested changes

2023-01-30 06:44 UTC, nyrahul commented on KubeArmor/monitor/systemMonitor.go
> +					delete(ctxReplayMap, ctx)
can you add a error print?

2023-01-30 06:44 UTC, nyrahul commented on KubeArmor/monitor/systemMonitor.go
> +					delete(ctxReplayMap, ctx)
can we add a warn print  here?

2023-01-30 06:44 UTC, nyrahul commented on KubeArmor/monitor/systemMonitor.go
> +			time.Sleep(time.Second * 10)
```suggestion
			time.Sleep(time.Second * 5)
```

2023-01-31 06:23 UTC, nyrahul approved these changes

2023-01-31 06:23 UTC, merged