feat: Added pprof and variable in makefile (WIP)
kubearmor/KubeArmor pull request #1091
Opened 2023-02-03 14:21 UTC by MdSahil-oss

Signed-off-by: MdSahil-oss <Mohdssahil1@gmail.com>

**Purpose of PR?**:

Fixes #1059

**Does this PR introduce a breaking change?**
no
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #1059
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-02-03 15:22 UTC, MdSahil-oss commented
@achrefbensaad I've added `pprof` support. can you please review it ? also Let me know how can I perform testing locally using minikube? confused about it.

2023-02-03 15:31 UTC, achrefbensaad commented
Hi @MdSahil-oss,  Sure will do. Yes you can use minikube to test locally.

2023-02-03 16:25 UTC, MdSahil-oss commented
@achrefbensaad Thanks for letting me know but what's the procedure to test my changes using minikube ?

2023-02-03 16:52 UTC, achrefbensaad commented
you can use this method.
1- use `build_kubearmor.sh` to generate a docker image, make sure to set the `REPO` env variable with the entended image name or it will create an image with the name `kubearmor/kubearmor`.
2- push the image to a container registry
3- using karmor cli, run `karmor install -i <your-image-name>`.

2023-02-04 13:06 UTC, MdSahil-oss commented
@achrefbensaad I tested `pprof` It's working fine according to me in this PR. Please review the flags that I've added

2023-02-04 14:12 UTC, MdSahil-oss commented
And confused about how to generate `pprof` enabled images because Dockerfile is just compiling the code with `make` command. Should I create a new Dockerfile which will create `pprof` enabled image when executing `build_kubearmor.sh` command

2023-02-06 09:37 UTC, achrefbensaad commented
Hi @MdSahil-oss , there is no need to create a new dockerfile, you cna modify the ci to build and push two images, one with pprof enabled and one without. Also can you please implement the rest of API's mentioned on the issue.

2023-02-07 13:30 UTC, MdSahil-oss commented
@achrefbensaad APIs like:
pprof.Handler("heap") -> /debug/pprof/heap
pprof.Handler("block") -> /debug/pprof/block
pprof.Handler("goroutine") -> /debug/pprof/goroutine
pprof.Handler("threadcreate") ->/debug/pprof/threadcreate
By default accessible that's why I didn't implement these.

2023-02-07 14:50 UTC, achrefbensaad commented
Ah ok, Ill test the PR. In the meantime, can you please rebase on top of main to resolve the gosec error.

2023-02-07 18:46 UTC, MdSahil-oss commented
@achrefbensaad The flow of generating `pprof` enabled images I can see is:
- First CI will trigger `build_kubearmor.sh` with a tag `<state/version>-debug` as an argument.
- By checking tag as an argument conditionally `build_kubearmor.sh` will call dockerfiles to create images.
- But if we want to create `pprof` enabled images then `ENABLE_PPROF` must be set to `true` by `ENABLE_PPROF=true make` command
As far as I can see dockerfiles is the only file which runs `make` command so i don't see anyother way to create pprof `enabled` images without creating a new dockerfile. If you have anyother method to do so then let me know will be glad to hear it :)

2023-02-08 07:15 UTC, achrefbensaad commented
you can pass the value of `ENABLE_PPROF` to the dockerfile and then pass it down to the makefile using env vars.
This is a link that shows how this can be achieved https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers

2023-02-08 11:50 UTC, MdSahil-oss commented
@achrefbensaad this PR needs to be reviewed now, Let me know if you find anything to be changed.

2023-02-09 09:36 UTC, achrefbensaad requested changes

2023-02-09 09:36 UTC, achrefbensaad commented on .github/workflows/ci-latest-release.yml
> +            docker image tag kubearmor/kubearmor:$value-debug kubearmor/kubearmor:stable-debug
We should add a new step rather then changing the existant step.

2023-02-09 09:36 UTC, achrefbensaad commented on Dockerfile
>  RUN make
you need to pass the variable to the make file.

2023-02-09 09:36 UTC, achrefbensaad commented on KubeArmor/build/kubearmor-test-docker.yaml
> +      - args:
No need to change this file.

2023-02-09 09:36 UTC, achrefbensaad commented on KubeArmor/build/build_kubearmor.sh
> +cd $ARMOR_HOME/..; docker build $DTAG -f Dockerfile --target kubearmor . $LABEL -e ENABLE_PPROF=false
the value should be handed down from the CI to this script, to the docker file , to the make file

2023-02-09 11:35 UTC, MdSahil-oss commented
@achrefbensaad I've updated the PR.

2023-02-10 11:24 UTC, achrefbensaad commented
Lets start by fixing the points above, then we will fix the other parts

2023-02-10 15:38 UTC, MdSahil-oss commented
@achrefbensaad I think I have fixed all the points that you mentioned :)

2023-02-10 16:01 UTC, achrefbensaad commented
Hi @MdSahil-oss , yes you have addressed the points I raised earlier, but some new issues were introduced also, please read the reviews above my comment.
Also. The CI should not generate only debug images (PPROF_ENABLED=true), we need to keep the normal release also (PPROF_ENABLED=false).

2023-02-13 09:55 UTC, MdSahil-oss commented
@achrefbensaad I think I have resolved all the reviews you did above.

2023-02-13 13:34 UTC, Ankurk99 requested changes
@MdSahil-oss Please address the unresolved commits.

2023-02-13 13:34 UTC, Ankurk99 commented on KubeArmor/build/build_kubearmor.sh
> +ENABLE_PPROF=true
why are you setting it to true here when it's already done in the ci manifest?

2023-02-13 17:51 UTC, MdSahil-oss commented
@achrefbensaad @achrefbensaad Now the value of `ENABLE_PPROF` is handed down from the CI to this script, to the docker file , to the make file as per your suggestion

2023-02-13 17:56 UTC, MdSahil-oss commented
And I kept `ENABLE_PPROF=false` for pprof disabled image.

2023-11-01 16:16 UTC, daemon1024 requested changes
@MdSahil-oss Sorry that we didn't follow up on this PR. The changes LGTM, can you please rebase your PR to resolve conflicts. Thank You.

2024-01-18 19:17 UTC, PrimalPimmy commented
Fixed in #1495 , closing this PR

2024-01-18 19:17 UTC, closed without merging