Increase buffer size to reduce dropped logs
kubearmor/KubeArmor pull request #1177
Opened 2023-03-20 12:52 UTC by Shreyas220

**Purpose of PR?**:

Fixes #1154 

- To address the potential issue of dropped logs when pushing logs into the channels , we increased the buffer size of the `LogStruct.Broadcast`, `AlertStruct.Broadcast`, and `MsgStruct.Broadcast` channels. This will allow the channels to hold more logs and alerts, reducing the likelihood of dropped data
 - Add logging to indicate if a log is dropped or not

2023-04-03 03:28 UTC, nyrahul requested changes

2023-04-03 03:28 UTC, nyrahul commented on KubeArmor/feeder/feeder.go
> +				kg.Print(fmt.Sprint("All channels in PushMessage busy Message dropped, Msg:", pbMsg))
```suggestion
				kg.Printf("msg channel busy, msg dropped, msg:%+v", pbMsg))
```

2023-04-03 03:28 UTC, nyrahul commented on KubeArmor/feeder/feeder.go
> +					kg.Print(fmt.Sprint("All channels in Pushlog busy Alert dropped, Alert:", pbAlert))
```suggestion
					kg.Printf("log channel busy, alert dropped. alert:%+v", pbAlert))
```

2023-04-03 03:28 UTC, nyrahul commented on KubeArmor/feeder/feeder.go
> +					kg.Print(fmt.Sprint("All channels in Pushlog busy Log dropped, Log:", pbLog))
```suggestion
					kg.Printf("log channel busy, log dropped. log:%+v", pbLog))
```

2023-04-03 03:31 UTC, nyrahul requested changes

2023-04-03 03:31 UTC, nyrahul commented on KubeArmor/feeder/feeder.go
> +	conn := make(chan *pb.Message, 100)
Pleae keep a constant.

```go
const int QueueSize = 100
```

2023-04-16 19:04 UTC, Ankurk99 requested changes

2023-04-16 19:04 UTC, Ankurk99 commented on KubeArmor/feeder/feeder.go
> +	LenMsg := len(MsgStructs)
Since it's not being exported, can we instead use lower-camel case `lenMsg`?

2023-07-20 05:52 UTC, daemon1024 commented
Please rebase and squash the PR. Thanks.

2023-07-31 06:07 UTC, daemon1024 approved these changes

2023-07-31 06:12 UTC, nyrahul approved these changes
LGTM

2023-07-31 06:12 UTC, merged