core: map containers to policy endpoint in non k8s env
kubearmor/KubeArmor pull request #1206
Opened 2023-04-24 18:52 UTC by daemon1024

This commit enables support for policy enforcement for unorchestrated containers where BPF LSM is the enforcer

**Purpose of PR?**:

Fixes #838 

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-04-26 09:53 UTC, nyrahul requested changes

2023-04-26 09:53 UTC, nyrahul commented on KubeArmor/core/crioHandler.go
> +		if !dm.K8sEnabled {
Can we remove this code duplication? Maybe use a common function call and use it from both crio and containerd handlers.

2023-04-26 09:53 UTC, nyrahul commented on KubeArmor/core/crioHandler.go
> +				}
It is usually preferred to reduce the nestings.
```suggestion
				if ep.EndPointName != dm.Containers[containerID].ContainerName {
				    continue
				}
				for i, c := range ep.Containers {
					if c != containerID {
					   continue
					}
					ep.Containers = append(ep.Containers[:i], ep.Containers[i+1:]...)
					break
				}
```

2023-05-15 08:00 UTC, DelusionalOptimist approved these changes
LGTM. :+1:

2023-05-15 14:42 UTC, Ankurk99 approved these changes
LGTM!

2023-05-15 15:56 UTC, nyrahul approved these changes
LGTM 👍 Great PR!

2023-05-15 15:57 UTC, nyrahul commented
I was hoping we can automate the system tests for this. Can we create another issue and handle it there since it would require provisioning of the resources?

2023-05-15 15:58 UTC, merged