docs: add updated KubeArmor Zoom link
kubearmor/KubeArmor pull request #1214
Opened 2023-05-04 15:41 UTC by Ankurk99

**Description**
Update KubeArmor Zoom link
We now have a Zoom redirection link: [zoom.kubearmor.io](zoom.kubearmor.io)

2023-05-05 05:16 UTC, nyrahul requested changes
- [ ] Please change the zoom meeting link in the kubearmor slack channel as well.

2023-05-05 05:16 UTC, nyrahul commented on README.md
> +- :speaking_head: [Zoom Link](zoom.kubearmor.io)
This link won't work.
```suggestion
- :speaking_head: [Zoom Link](https://zoom.kubearmor.io)
```

2023-05-05 06:56 UTC, Ankurk99 commented
>  Please change the zoom meeting link in the kubearmor slack channel as well.

I have updated the zoom link but can't edit the pinned message @nyrahul

2023-06-12 11:29 UTC, DelusionalOptimist commented
Folks, let's close this?
Docs were updated in - https://github.com/kubearmor/KubeArmor/pull/1243
Also #general in KubeArmor slack already has the new zoom and meeting minutes link set in bookmarks. Ig we can unpin the message @Ankurk99 is referring?

2023-06-12 12:30 UTC, closed without merging