feat(core): disable visibility globally
kubearmor/KubeArmor pull request #1220
Opened 2023-05-10 08:11 UTC by daemon1024

**Purpose of PR?**:

Fixes #1208 

**Does this PR introduce a breaking change?**

This pR updates the way we handle visibility annotations.

We now use configmap/global config value as the default source of truth and don't annotate each and every namespace.

Any changes to the configmap will update  all the namespaces visibility that doesn't have annotation.

If anyone needs to set a custom visibility annotation for some namespace they can annotate the namespace and it will overrule the global default

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-05-10 15:06 UTC, achrefbensaad requested changes
LGTM, Can you please add ginkgo tests to the PR.

2023-05-10 15:41 UTC, DelusionalOptimist reviewed
Looking good. Just some nitpicks.

2023-05-10 15:41 UTC, DelusionalOptimist commented on KubeArmor/core/kubeUpdate.go
> +				key := "kubearmor-visibility"
Since we're using this key repeatedly, let's make it a global constant?

2023-05-10 15:41 UTC, DelusionalOptimist commented on KubeArmor/core/kubeUpdate.go
> +func (dm *KubeArmorDaemon) updatVisibilityWithCM(cm *corev1.ConfigMap, action string) {
```suggestion
func (dm *KubeArmorDaemon) updateVisibilityWithCM(cm *corev1.ConfigMap, action string) {
```

2023-05-10 15:41 UTC, DelusionalOptimist commented on deployments/go.mod
> +	github.com/kubearmor/KubeArmor/pkg/KubeArmorController v0.0.0-00010101000000-000000000000
Is this change intentional? (Though it doesn't matter because we have a replace directive for this anyway)

2023-05-10 15:41 UTC, DelusionalOptimist commented on KubeArmor/monitor/systemMonitor.go
> +		mon.Logger.Printf("Updated visibiliy map with key=%+v for cid %s", nsKey, mon.NsMap[nsKey])
```suggestion
		mon.Logger.Printf("Updated visibility map with key=%+v for cid %s", nsKey, mon.NsMap[nsKey])
```

2023-05-12 18:59 UTC, DelusionalOptimist approved these changes
LGTM. :+1:

2023-05-12 21:21 UTC, achrefbensaad approved these changes
LGTM!, few lint issues

2023-05-12 21:21 UTC, achrefbensaad commented on tests/util/karmorlog.go
> +func IsOperationsExpected(operations []string, expected []string) bool {
Can you please handle Lint

2023-05-12 21:21 UTC, achrefbensaad commented on tests/util/kartutil.go
> +type ConfigMapData struct {
here also

2023-05-15 06:47 UTC, merged