Default Posture logs bug
kubearmor/KubeArmor pull request #1324
Opened 2023-07-21 05:19 UTC by Aryan-sharma11

**Purpose of PR?**:

Fixes #1250 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_
In the current design for `Operation == File/Process` we follow  the following design.
![image](https://github.com/kubearmor/KubeArmor/assets/54109867/2881669f-6bb8-4a4e-ab88-0ea436bf5d17)

**what this PR introduces is, a new check for checking if the policy is matched earlier.**

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-07-23 14:36 UTC, daemon1024 requested changes
Thanks for finding the bug, the changes make sense to me 👌🏽

2023-07-23 14:36 UTC, daemon1024 commented on KubeArmor/feeder/policyMatcher.go
> -					// defaultPosture = audit
Let's keep this comment.

And also, let's add a commet that we only apply default posture whe log.type isn't yet known.

2023-07-24 09:30 UTC, daemon1024 approved these changes

2023-07-31 06:15 UTC, nyrahul approved these changes

2023-07-31 06:17 UTC, merged