Doc improvements: typos, grammar, formatting
kubearmor/KubeArmor pull request #1351
Opened 2023-08-07 18:39 UTC by HighnessAtharva

2023-08-22 04:46 UTC, Ankurk99 requested changes
Thanks for the PR @HighnessAtharva. There are some nits mentioned inlined, PTAL.

2023-08-22 04:46 UTC, Ankurk99 commented on README.md
>  ### Biweekly Meetup
```suggestion
### Biweekly Meeting
```
This will improve our clomonitor score as it checks for this keyword.

2023-08-22 04:46 UTC, Ankurk99 commented on README.md
> +* :page_facing_up: Minutes: [Document](https://docs.google.com/document/d/1IqIIG9Vz-PYpbUwrH0u99KYEM1mtnYe6BHrson4NqEs/edit)
```suggestion
* :page_facing_up: Meeting minutes: [Document](https://docs.google.com/document/d/1IqIIG9Vz-PYpbUwrH0u99KYEM1mtnYe6BHrson4NqEs/edit)
```

2023-08-22 04:46 UTC, Ankurk99 commented on SECURITY.md
> +    - Please include the requested information listed below (as much as you can provide) to help us better understand the nature and scope of the possible issue:
What's the difference between using `-` and `*` in md :smile: ? Because above you reversed the order.

2023-08-22 04:46 UTC, Ankurk99 commented on getting-started/FAQ.md
> +* No alerting of LSM violation on managed cloud platforms: By default, LSMs send logs to kernel audit, which is not available on most managed cloud platforms.
It should be auditd (i.e. audit daemon)

2023-08-22 04:46 UTC, Ankurk99 commented on getting-started/FAQ.md
> +* Pod Security Context does not manage abstractions. As an example, you might have two nodes with Ubuntu, and two nodes with Bottlerocket. Ubuntu, by default, has AppArmor and Bottlerocket has BPF-LS
```suggestion
* The Pod Security Context does not handle abstractions. For instance, consider a scenario where you have a node running Ubuntu and another node running Bottlerocket. Ubuntu inherently utilizes AppArmor, while Bottlerocket employs BPF-LSM and SELinux as its default LSMs. KubeArmor internally selects the appropriate primitives for enforcement, eliminating the need for users to explicitly specify the enforcement method.
```

2023-08-22 04:46 UTC, Ankurk99 commented on getting-started/FAQ.md
> +`karmor log` has the following filter to provide more granularity:
```suggestion
`karmor logs` has the following filter to provide more granularity:
```

Please update `karmor log` to `karmor logs` at other places too

2023-08-22 04:46 UTC, Ankurk99 commented on getting-started/FAQ.md
>  `karmor log --pod <pod_name>`
```suggestion
`karmor logs --pod <pod_name>`  
```

2023-08-22 04:46 UTC, Ankurk99 commented on getting-started/FAQ.md
> -  $ sudo vi /etc/default/grub
Good find!

2023-08-22 04:46 UTC, Ankurk99 commented on getting-started/kubearmor_visibility.md
> +### Example: WordPress-MySQL
as it's a deployment name, let's keep it the same

2023-08-22 04:58 UTC, HighnessAtharva commented on SECURITY.md
> +    - Please include the requested information listed below (as much as you can provide) to help us better understand the nature and scope of the possible issue:
I think the `-` is a more conventional way to list items in Markdown.

2023-08-22 04:58 UTC, HighnessAtharva commented
@Ankurk99 I believe most issues have been resolved. Thank you for pointing it out.

2023-08-22 05:06 UTC, Ankurk99 commented on SECURITY.md
> +    - Please include the requested information listed below (as much as you can provide) to help us better understand the nature and scope of the possible issue:
I see, let's stick to `-` only throughout the document then. Please reverse the above changes regarding the same.

2023-08-22 05:08 UTC, HighnessAtharva commented on SECURITY.md
> +    - Please include the requested information listed below (as much as you can provide) to help us better understand the nature and scope of the possible issue:
I think I have reverted the change. Please review. List items are prefixed with `-` at the moment.

2023-08-22 05:11 UTC, Ankurk99 commented on README.md
> +* :speaking_head: [Zoom Link](http://zoom.kubearmor.io)
here, pls revert the bullet type to `-`

2023-08-22 05:15 UTC, HighnessAtharva commented on README.md
> +* :speaking_head: [Zoom Link](http://zoom.kubearmor.io)
> here, pls revert the bullet type to `-`

Done

2023-08-23 20:00 UTC, Ankurk99 commented
Hey @HighnessAtharva, there are still a few review comments left, can you please address those? Also please sign the commit. 
You will also need to resolve the conflicts :grimacing:

2023-08-30 20:10 UTC, HighnessAtharva commented
Signed-off-by: HighnessAtharva [highnessatharva@gmail.com](mailto:highnessatharva@gmail.com)

2023-08-30 20:11 UTC, HighnessAtharva commented
> Hey @HighnessAtharva, there are still a few review comments left, can you please address those? Also please sign the commit. You will also need to resolve the conflicts 😬

Resolved issues, should be fine to merge now?

2023-09-01 21:05 UTC, rootxrishabh commented
> > Hey @HighnessAtharva, there are still a few review comments left, can you please address those? Also please sign the commit. You will also need to resolve the conflicts 😬
> 
> Resolved issues, should be fine to merge now?

Hi @HighnessAtharva, You have to squash the commits you have made and use the --signoff switch while committing again, this will squash your commits and pass the DCO checks.

2025-05-12 12:11 UTC, closed without merging