fix(core): fix owner name info
kubearmor/KubeArmor pull request #1361
Opened 2023-08-11 10:41 UTC by Ankurk99

**Purpose of PR?**:
We were not getting the Owner name:
```
  "Owner": {
    "Ref": "Deployment",
    "Namespace": "default"
  },
```

Fixes: https://github.com/orgs/kubearmor/projects/17?pane=issue&itemId=35639507

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Tested locally, was getting the Owner name info.

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix.
- [x] New feature (non-breaking change which adds functionality) - NA
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) - NA
- [x] This change requires a documentation update - NA
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Commit has unit tests - NA
- [x] Commit has integration tests - NA

2023-08-11 10:42 UTC, daemon1024 approved these changes

2023-08-11 10:43 UTC, daemon1024 commented
Can we add a test for this?

2023-08-11 10:46 UTC, Shreyas220 requested changes
pod.Metadata["deploymentName"]  is used multiple times in this function please update at those places as well

2023-08-14 06:33 UTC, nyrahul approved these changes

2023-08-14 06:40 UTC, Shreyas220 approved these changes

2023-08-14 06:40 UTC, merged