feat(docs): ArtifactHub Badge and ROADMAP.md Added
kubearmor/KubeArmor pull request #1363
Opened 2023-08-12 16:55 UTC by rootxrishabh

**Purpose of PR?**:
This PR will introduce a series of changes that will increase the CLOMonitor score for KubeArmor, the goal is to achieve a score of 100.

Fixes #1353 

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for the reviewer?** :  **WIP, DO NOT MERGE!**

_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-08-14 06:36 UTC, kranurag7 reviewed
- Let's wait for [this](https://github.com/kubearmor/kubearmor-client/pull/340) changes to be merged before adding artifact-hub labels on the repo. 
- Let's reference all the projects at once https://github.com/orgs/kubearmor/projects?query=is:open because as of now, I don't see anything open on the second link. We also have project targeting specific sections like the capabilities one you see [here](https://github.com/orgs/kubearmor/projects?query=is:open)

2023-08-14 09:41 UTC, Aryan-sharma11 requested changes

2023-08-14 09:41 UTC, Aryan-sharma11 commented on ROADMAP.md
Thanks for the PR @rootxrishabh,  can we have the roadmap section in KubeArmor `README.md` itself instead of having a seperate doc `ROADMAP.md`.  For [reference](https://clomonitor.io/docs/topics/checks/#roadmap)

2023-08-14 19:42 UTC, nyrahul commented on ROADMAP.md
Yep, it makes sense to have the Roadmap as part of the primary `README.md` since it is simply a link to the projects page.

2023-08-19 17:37 UTC, rootxrishabh commented
> * Let's wait for [this](https://github.com/kubearmor/kubearmor-client/pull/340) changes to be merged before adding artifact-hub labels on the repo.
> * Let's reference all the projects at once https://github.com/orgs/kubearmor/projects?query=is:open because as of now, I don't see anything open on the second link. We also have project targeting specific sections like the capabilities one you see [here](https://github.com/orgs/kubearmor/projects?query=is:open)

@kranurag7 agreed. In that case, should I keep [this](https://github.com/orgs/kubearmor/projects/9) in the roadmap or specific [section project targeting](https://github.com/orgs/kubearmor/projects?query=is:open)?

2023-08-20 13:52 UTC, kranurag7 commented
@rootxrishabh let's keep [this](https://github.com/orgs/kubearmor/projects?query=is%3Aopen) one.

2023-08-22 06:00 UTC, Aryan-sharma11 commented
@rootxrishabh Can you please handle the [DCO](https://github.com/kubearmor/KubeArmor/pull/1363/checks?check_run_id=16036352776) and squash commits.

2023-08-22 22:24 UTC, rootxrishabh commented
@Aryan-sharma11 that's a good idea, also I removed the FOSSA badge from this PR as it is being handled here #1378

2023-09-08 16:18 UTC, closed without merging

2023-09-08 16:20 UTC, rootxrishabh commented
Hey guys, I accidentally closed the PR can someone reopen it?

2023-09-08 16:32 UTC, kranurag78 commented
AFAIK, We cannot open a pull request from our side. You can create it from your side using the same branch.

2023-09-08 16:36 UTC, rootxrishabh commented
No problem : )