fix(refactor): change KubeArmor default namespace to "kubearmor"
kubearmor/KubeArmor pull request #1372
Opened 2023-08-18 05:53 UTC by Ankurk99

**Purpose of PR?**:

Fixes #1167 

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Tested locally on k3s - Observability and enforcement working

**Additional information for reviewer?** :
Once merged this needs to be tested on all the platforms.

**Checklist:**
- [x] Bug fix. Fixes #1167 
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`

2023-08-18 06:08 UTC, achrefbensaad commented
you need to add namespace creation in the CI

2023-09-06 09:34 UTC, achrefbensaad requested changes, later dismissed
LGTM, Please squash the commits

2023-09-22 06:59 UTC, daemon1024 approved these changes

2023-09-22 07:27 UTC, DelusionalOptimist approved these changes

2023-09-22 07:31 UTC, merged