fix(systemmonitor): bug related to syscall events handling
kubearmor/KubeArmor pull request #1373
Opened 2023-08-18 09:15 UTC by Ankurk99

**Purpose of PR?**:

Fixes #1356 

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Tested locally on k3s.
 
cc: @achrefbensaad 

**Checklist:**
- [x] Bug fix.

2023-08-19 03:43 UTC, nyrahul reviewed
Mostly LGTM. One minor review comment. Please check.

2023-08-19 03:43 UTC, nyrahul commented on KubeArmor/monitor/systemMonitor.go
> +				mon.SyscallChannel <- dataRaw
It would be great to print the container name/id in the warning on line 610.

2023-08-22 17:04 UTC, nyrahul approved these changes

2023-08-22 17:05 UTC, daemon1024 requested changes
I tried the image, I don't think this is working as expected when the problem occurs. Let's keep it on hold till everything is verified.

2023-11-21 06:27 UTC, closed without merging