Listing the policies applied on containers in Systemd mode
kubearmor/KubeArmor pull request #1396
Opened 2023-09-05 12:14 UTC by Aryan-sharma11

**Purpose of PR?**:

Fixes #1311 

**Does this PR introduce a breaking change?** NA

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-09-22 04:06 UTC, daemon1024 requested changes
Did a quick review, one review in line. Can you handle lint errors as well?

2023-09-22 04:06 UTC, daemon1024 commented on protobuf/karmor.proto
> +message ContainerData {
Why is this a new proto? Shouldn't it be part of the Policy Proto? WDYT?

2023-10-09 06:02 UTC, ShubhamTatvamasi commented
@Aryan-sharma11 can you please rebase and run the CI tests again?

2023-10-17 06:01 UTC, daemon1024 approved these changes

2023-10-17 13:47 UTC, DelusionalOptimist requested changes
@Aryan-sharma11 Mostly looking good. Please find some comments inline.

Though I couldn't tryout probe with kubearmor-client, I did manage to get the probe output with grpcurl.


![image](https://github.com/kubearmor/KubeArmor/assets/54525605/4b5daace-5aa3-47de-a3ca-aeb329def05d)

In the above, I created a policy for ubuntu-vm but then deleted it. However it still showed up in the response.
Also, ubuntu-3 container didn't exist but it still showed up in the "containerMap" as it had a policy. This is fine but IMO it shouldn't have policyEnabled = 1 as this container doesn't exist. Though I think this information is taken directly from stated stored in KubeArmor but we might need to handle these edge cases either here or in client.

2023-10-17 13:47 UTC, DelusionalOptimist commented on KubeArmor/core/karmorprobedata.go
> +		}
Are we looking for a specific label to match here? Why do we need this loop?
Also, KubeArmor only protects a single node anyways. The name is stored in `dm.Node.NodeName`. Shouldn't we directly use that?

2023-10-17 13:47 UTC, DelusionalOptimist commented on KubeArmor/core/karmorprobedata.go
> +	var containerMap map[string]*pb.ContainerData
This declaration is not needed.
```suggestion
```

2023-10-17 13:47 UTC, DelusionalOptimist commented on protobuf/go.mod
> +	github.com/golang/protobuf v1.5.3
Can we stick to `google.golang.org/protobuf`? Mixing protobuf dependecies has led to terrible runtime panics in the past : (

2023-10-17 13:47 UTC, DelusionalOptimist commented on .github/workflows/ci-test-ginkgo.yml
Also need to update other workflows where ginkgo runs. For instance `ci-latest-release.yaml`, `ci-test-controllers`.

2023-10-17 13:47 UTC, DelusionalOptimist commented on tests/util/kartutil.go
> +func CommandParse(cmdstr string) (string, error) {
```suggestion
func RunDockerCommand(cmdstr string) (string, error) {
```

2023-10-18 05:41 UTC, Aryan-sharma11 commented
> @Aryan-sharma11 Mostly looking good. Please find some comments inline.
> 
> Though I couldn't tryout probe with kubearmor-client, I did manage to get the probe output with grpcurl.
> 
> ![image](https://user-images.githubusercontent.com/54525605/275853460-4b5daace-5aa3-47de-a3ca-aeb329def05d.png)
> 
> In the above, I created a policy for ubuntu-vm but then deleted it. However it still showed up in the response. Also, ubuntu-3 container didn't exist but it still showed up in the "containerMap" as it had a policy. This is fine but IMO it shouldn't have policyEnabled = 1 as this container doesn't exist. Though I think this information is taken directly from stated stored in KubeArmor but we might need to handle these edge cases either here or in client.



> @Aryan-sharma11 Mostly looking good. Please find some comments inline.
> 
> Though I couldn't tryout probe with kubearmor-client, I did manage to get the probe output with grpcurl.
> 
> ![image](https://user-images.githubusercontent.com/54525605/275853460-4b5daace-5aa3-47de-a3ca-aeb329def05d.png)
> 
> In the above, I created a policy for ubuntu-vm but then deleted it. However it still showed up in the response. Also, ubuntu-3 container didn't exist but it still showed up in the "containerMap" as it had a policy. This is fine but IMO it shouldn't have policyEnabled = 1 as this container doesn't exist. Though I think this information is taken directly from stated stored in KubeArmor but we might need to handle these edge cases either here or in client.

Yes In the client we handle this case of policy being there and container not being present as we match the container Map with the Container List so only the active containers are shown.  for [ref](https://github.com/kubearmor/kubearmor-client/pull/372/files#diff-0b3ca41e370fff5ec9331a998f39c4c430b7bac2ceb0318fcb2a98f31e178b03R631).

2023-10-18 15:01 UTC, DelusionalOptimist approved these changes
LGTM. :rocket:

2023-10-18 15:01 UTC, merged