ensuring PPID to be 0 when HOSTPPID is assigned to PPID
kubearmor/KubeArmor pull request #1411
Opened 2023-09-13 09:09 UTC by Prateeknandle

**Purpose of PR?**:
`PPID` inside the container takes `PPID` of runc during `kubectl exec` therefore we add a check when `PPID == HOSTPPID` we make `PPID = 0`

Fixes #1388 

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
tested locally, during kubectl exec `PPID` is 0 and for other process like `ls`, `PPID` has its original value
log for kubectl exec:
```
== Log / 2023-09-13 08:49:05.195945 ==
ClusterName: default
HostName: prateek-lenovo-ideapad-310-15isk
NamespaceName: default
PodName: nginx-86c557dcf4-fs26c
ContainerName: 09c3cbf01faacf6e6e3246200a8341138b2e6aea9ed7876d05f0144092bdc8c1
ContainerID: 09c3cbf01faacf6e6e3246200a8341138b2e6aea9ed7876d05f0144092bdc8c1
Type: ContainerLog
Source: /var/lib/rancher/k3s/data/8a84c92c5c245778005e7fa2a03c4d84118fde366594fe826bcd7351d8b88d21/bin/runc
Resource: /bin/bash
Operation: Process
Data: syscall=SYS_EXECVE
Result: Passed
HostPID: 211775
HostPPID: 211772
PID: 360
PPID: 0
ParentProcessName: /var/lib/rancher/k3s/data/8a84c92c5c245778005e7fa2a03c4d84118fde366594fe826bcd7351d8b88d21/bin/runc
ProcessName: /bin/bash

```

**Additional information for reviewer?** :
during `json.Marshal`, due to `omitempty` tag `PPID` with value 0 was not shown in the logs therefore added `sed` command to remove the omitempty tag from the `.pb.go` file.

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-09-14 06:22 UTC, nyrahul requested changes, later dismissed

2023-09-14 06:22 UTC, nyrahul commented on protobuf/Makefile
> +	sed -i 's/\bPPID,omitempty\b/PPID,/' kubearmor.pb.go
Please add UID as well.

2023-09-14 10:17 UTC, daemon1024 approved these changes
LGTM, one small nit

2023-09-14 10:17 UTC, daemon1024 commented on protobuf/kubearmor.pb.go
> +// 	protoc        v3.19.4
Can you use latest protoc? that will avoid these changes latest protoc seems to be v4.23.4

2023-09-14 11:14 UTC, daemon1024 approved these changes
LGTM 👌🏽 

Do we need to update protobufs on client side to support the zero values? Or will it work OOB.

2023-09-14 11:19 UTC, Prateeknandle commented
> Do we need to update protobufs on client side to support the zero values? Or will it work OOB.

Yes we have to update protobufs on client side as well

2023-09-16 12:09 UTC, daemon1024 approved these changes

2023-09-16 12:10 UTC, merged

2023-09-16 12:10 UTC, daemon1024 commented
Can you please make updates to kubearmor client as well?