feat(config):update default visibility to disable file-based telemetry
kubearmor/KubeArmor pull request #1444
Opened 2023-10-05 08:35 UTC by Ankurk99

**Purpose of PR?**:
Disable file-based telemetry by default

Fixes #1442 

**Does this PR introduce a breaking change?**
Yes, need to update the CI test cases. Let's first test if the CI is working fine and actually breaks with updating the visibility.

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`

2023-10-06 11:55 UTC, nyrahul requested changes

2023-10-06 11:55 UTC, nyrahul commented on KubeArmor/config/config.go
> +	visStr := flag.String(ConfigVisibility, "process,network,capabilities", "Container Visibility to use [process,file,network,capabilities,none]")
There is no need to change this, since this will be overridden by the value passed from the configmap.

2023-10-06 11:55 UTC, nyrahul commented on deployments/helm/KubeArmor/README.md
> +        Container Visibility to use [process,file,network,capabilities,none] (default "process,network,capabilities")
```suggestion
        Container Visibility to use [process,network,capabilities,none] (default "process,network,capabilities")
```

2023-10-10 06:03 UTC, daemon1024 requested changes

2023-10-10 06:03 UTC, daemon1024 commented on deployments/helm/KubeArmor/README.md
> +        Container Visibility to use [process,network,capabilities,none] (default "process,network,capabilities")
We should not remove these, folks still may use file

2023-10-10 07:59 UTC, daemon1024 commented on deployments/helm/KubeArmor/README.md
> +        Container Visibility to use [process,network,capabilities,none] (default "process,network,capabilities")
```suggestion
        Container Visibility to use [process,file,network,capabilities,none] (default "process,network")
```

2023-10-10 08:40 UTC, daemon1024 approved these changes

2023-10-11 12:53 UTC, nyrahul approved these changes
LGTM

2023-10-11 12:53 UTC, merged