Updated the GithubAction Workflows to Ubuntu-22.04
kubearmor/KubeArmor pull request #1490
Opened 2023-11-01 14:49 UTC by Srijan-SS02

**Purpose of PR?**:

Fixes #1433

**Does this PR introduce a breaking change?**
No

**Additional information for reviewer?** :

_Mention if this PR is part of any design or a continuation of previous PRs_
#1434 

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Commit has unit tests
- [x] Commit has integration tests

2023-11-01 15:10 UTC, Srijan-SS02 commented
Hey @ShubhamTatvamasi , please review!

2023-11-01 16:11 UTC, ShubhamTatvamasi commented
@daemon1024 how can we test it's CI?

2023-11-01 16:15 UTC, daemon1024 requested changes
Thanks for the PR. Please find the requested changes

2023-11-01 16:15 UTC, daemon1024 commented on .github/workflows/ci-latest-helm-chart-release.yaml
> +        runtime: ["docker", "containerd", "crio"]
```suggestion
```

We don't runtime matrix for anything other than the test where we already have it. Please don't add runntime variables or fail fast variables. It will affect the flow of the release.

2023-11-01 16:16 UTC, daemon1024 commented on .github/workflows/ci-latest-helm-chart-release.yaml
> +        runtime: ["docker", "containerd", "crio"]
Please signoff your commit as well. Check DCO Action failure logs.

2023-11-04 20:38 UTC, Srijan-SS02 commented on .github/workflows/ci-latest-helm-chart-release.yaml
> +        runtime: ["docker", "containerd", "crio"]
Hello @daemon1024, thanks for reviewing. I have made the changes that you asked for, runtime and fail fast is removed from wherever it was not earlier there in the workflow. Also I have signed off my commit.

2023-11-04 20:39 UTC, Srijan-SS02 commented
@daemon1024 @ShubhamTatvamasi Please review again.

2023-11-05 09:21 UTC, ShubhamTatvamasi requested changes

2023-11-05 09:21 UTC, ShubhamTatvamasi commented on .github/workflows/ci-test-ginkgo.yml
> +        os: [ubuntu-22.04]
Don't we need matrix here?

2023-11-08 06:48 UTC, Srijan-SS02 commented
Hey @ShubhamTatvamasi  @daemon1024 , anything on this that I need to update ?

2023-11-08 13:23 UTC, daemon1024 requested changes

2023-11-08 13:23 UTC, daemon1024 commented on .github/workflows/ci-test-helm-charts.yml
>      name: Helm Chart Tests / ubuntu 20.04
```suggestion
    name: Helm Chart Tests / < matrix variable >
```

2023-11-08 13:23 UTC, daemon1024 commented on .github/workflows/ci-test-ginkgo.yml
> +        os: [ubuntu-22.04]
It's already under matrix

2023-11-08 13:24 UTC, daemon1024 commented
@Srijan-SS02 a small nit, can you handle that? Will wait for the CI to finish to validate changes

2023-11-09 10:05 UTC, Srijan-SS02 commented
@daemon1024 are you talking about [ci-test-controllers,](https://github.com/kubearmor/KubeArmor/actions/runs/6757056141/job/18483905025?pr=1490) [ci-test-ubi-ginkgo](https://github.com/kubearmor/KubeArmor/actions/runs/6757056147/job/18483905379?pr=1490), and [ci-test-ginkgo](https://github.com/kubearmor/KubeArmor/actions/runs/6757056138/job/18483904989?pr=1490) checks that did not pass successfully? If yes, then I can give a try to fix it up but will need some time. 
If it's something else, then let me know!

2023-11-11 16:21 UTC, Srijan-SS02 commented
@daemon1024  can you please approve the workflows, as I have committed the changes you have suggested.

2023-11-13 04:05 UTC, ShubhamTatvamasi commented
@Srijan-SS02 please rebase your branch and request for re-review.

2023-11-17 19:38 UTC, Srijan-SS02 commented
Created a fresh PR #1513

2023-11-17 19:38 UTC, closed without merging