WIP: Perf improve
kubearmor/KubeArmor pull request #1508
Opened 2023-11-15 14:28 UTC by daemon1024

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-11-27 17:00 UTC, nyrahul requested changes

2023-11-27 17:00 UTC, nyrahul commented on KubeArmor/BPF/system_monitor.c
> +    if (get_kubearmor_config(_MONITOR_HOST) && pid_ns == PROC_PID_INIT_INO)
I think we should reverse the checks for performance reasons.
```suggestion
    if (pid_ns == PROC_PID_INIT_INO && get_kubearmor_config(_MONITOR_HOST))
```

2023-11-27 17:00 UTC, nyrahul commented on KubeArmor/BPF/system_monitor.c
> +        if (!bpf_map_lookup_elem(&pid_ns_map, &pid))
Isn't this change completely changing the semantics? reversing the check.

2023-11-27 17:00 UTC, nyrahul commented on KubeArmor/BPF/system_monitor.c
> +        if (!bpf_map_lookup_elem(&pid_ns_map, &pid))
Oh I see the code below and it makes sense

2023-11-27 17:00 UTC, nyrahul commented on KubeArmor/BPF/system_monitor.c
> +    _ENFORCER_BPFLSM = 2,
Having MONITOR and ENFORCER in the same enum might be a problem in the future. Won't we need enforcer and Monitor enabled at the same time?

2023-11-27 17:07 UTC, daemon1024 commented on KubeArmor/BPF/system_monitor.c
> +    _ENFORCER_BPFLSM = 2,
These enums are not values but indexes of the map.

All three of the values are configured independently and serve different usecases. It's not an if else case.

2023-11-27 19:29 UTC, daemon1024 commented
Closes https://github.com/kubearmor/KubeArmor/issues/1356

2023-11-28 06:14 UTC, nyrahul approved these changes
LGTM

2023-11-28 06:35 UTC, merged