feat : add flag for defaultposture log in Apparmor
kubearmor/KubeArmor pull request #1537
Opened 2023-12-06 19:06 UTC by Aryan-sharma11

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2023-12-07 04:12 UTC, daemon1024 requested changes

2023-12-07 04:12 UTC, daemon1024 commented on KubeArmor/feeder/feeder.go
> +	if (cfg.GlobalCfg.EnforcerAlerts && fd.Enforcer == "BPFLSM" && log.Enforcer != "BPFLSM") || (fd.Enforcer == "AppArmor" && !cfg.GlobalCfg.DefaultPostureLogs && strings.Contains(log.PolicyName, "Defau
Please add a comment explaining what's happening here.

Both for BPFLSM and AppArmor.
This has become a very confusing if condition now.

2023-12-13 10:05 UTC, daemon1024 approved these changes

2023-12-13 11:12 UTC, DelusionalOptimist approved these changes

2023-12-13 11:12 UTC, merged