Added CO_RE archive in kubearmor release
kubearmor/KubeArmor pull request #1711
Opened 2024-04-03 06:32 UTC by Aryan-sharma11

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2024-04-03 11:26 UTC, DelusionalOptimist commented
@Aryan-sharma11 it's still failing as KubeArmor is trying to look for the BPF object in /opt/kubearmor/BPF however it is present in /opt/kubearmor : (
![image](https://github.com/kubearmor/KubeArmor/assets/54525605/e7ab0940-adf8-4964-8c1f-9b06cec189d4)

2024-04-03 12:47 UTC, DelusionalOptimist approved these changes, later dismissed
LGTM.

2024-04-03 15:18 UTC, daemon1024 requested changes
- Move dependecies to suggestions or recommendations (whichever appropriate)
- Modify Post Install Script to run make for BPF only if BTF is not present
- Update Docs to reflect all of this

2024-04-05 06:12 UTC, daemon1024 requested changes

2024-04-05 06:12 UTC, daemon1024 commented on getting-started/kubearmor_vm.md
>    > Note that the above automatically installs `bpfcc-tools` with our package, but your distribution might have an older version of BCC. In case of errors, consider installing `bcc` from [source](htt
We don't need bcc anymore

2024-04-05 06:12 UTC, daemon1024 commented on getting-started/kubearmor_vm.md
>    sudo apt install ./kubearmor_${VER}_linux-amd64.deb
Let's use no install recommends by default

2024-04-05 06:12 UTC, daemon1024 commented on getting-started/kubearmor_vm.md
> +  > Note that the above automatically installs the recommended packages by default, which may not be necessary in some cases as we ship object files along with package file, so to avoid it you can us
Modify note to talk about if you don't have BTF remove the flag usage

2024-04-05 06:12 UTC, daemon1024 commented on KubeArmor/packaging/post-install.sh
>  if [ -x "$(command -v semanage)" ]; then
Only run this if BPF LSM is not available

2024-04-09 15:30 UTC, daemon1024 approved these changes
LGTM 👌🏽

2024-04-09 15:30 UTC, DelusionalOptimist approved these changes

2024-04-09 15:32 UTC, merged