feat-wip: special presets
kubearmor/KubeArmor pull request #1743
Opened 2024-04-29 13:56 UTC by daemon1024

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2024-09-20 09:40 UTC, daemon1024 commented
Ref https://github.com/kubearmor/KubeArmor/issues/1295

// @rksharma95

2024-11-13 13:23 UTC, rootxrishabh commented
Facing bpf module read error -

`
2024-11-13 13:16:31.661337	ERROR	Failed to initialize BPF (bpf module is nil program kretprobe__rmdir: load program: permission denied: 1256: (1d) if r3 == r1 goto pc+1182   ; R1_w=scalar() R3_w=scalar(): ; bpf (truncated, 1008 line(s) omitted))
github.com/kubearmor/KubeArmor/KubeArmor/log.Errf
	/usr/src/KubeArmor/KubeArmor/log/logger.go:108
github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).InitSystemMonitor
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:261
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:555
main.main
	/usr/src/KubeArmor/KubeArmor/main.go:79
runtime.main
	/usr/local/go/src/runtime/proc.go:271
2024-11-13 13:16:31.661415	ERROR	Failed to initialize KubeArmor Monitor
github.com/kubearmor/KubeArmor/KubeArmor/log.Err
	/usr/src/KubeArmor/KubeArmor/log/logger.go:103
github.com/kubearmor/KubeArmor/KubeArmor/feeder.(*Feeder).Err
	/usr/src/KubeArmor/KubeArmor/feeder/feeder.go:439
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:556
main.main
	/usr/src/KubeArmor/KubeArmor/main.go:79
runtime.main
	/usr/local/go/src/runtime/proc.go:271
`

Environment - 
 - K8s -> GKE
 - Container Runtime -> containerd://1.7.22
 - Kernel Version -> 6.1.100+
 - Operating system -> Container-Optimized OS from Google

2024-12-23 08:34 UTC, Aryan-sharma11 commented on KubeArmor/BPF/anonmapexec.bpf.c
> +        return -13;
```suggestion
        return -EPERM;
```

2024-12-23 08:44 UTC, Aryan-sharma11 commented on KubeArmor/BPF/protectenv.bpf.c
> +    return -13;
```suggestion
    return -EPERM;
```

2024-12-23 08:50 UTC, Aryan-sharma11 commented on KubeArmor/core/kubeArmor.go
> +		dm.Logger.Errf("Failed to destry preset (%s)", err.Error())
```suggestion
		dm.Logger.Errf("Failed to destroy preset (%s)", err.Error())
```

2024-12-23 11:00 UTC, Aryan-sharma11 requested changes

2024-12-23 11:00 UTC, Aryan-sharma11 commented on KubeArmor/feeder/feeder.go
> +		kg.Printf("PRESET LOG 2: %+v\n", log)
is this a debug statement or is it supposed to be `PRESET LOG 2` only?

2024-12-23 11:00 UTC, Aryan-sharma11 commented on KubeArmor/presets/anonmapexec/preset.go
> +		// it's based on actibe enforcer, it might possible that node support bpflsm but
```suggestion
		// it's based on active enforcer, it might possible that node support bpflsm but
```

2024-12-23 11:00 UTC, Aryan-sharma11 commented on KubeArmor/presets/filelessexec/preset.go
> +		// it's based on actibe enforcer, it might possible that node support bpflsm but
```suggestion
		// it's based on active enforcer, it might possible that node support bpflsm but
```

2024-12-23 11:00 UTC, Aryan-sharma11 commented on KubeArmor/BPF/filelessexec.bpf.c
> +static __always_inline int is_dev_shm(char *name) {
this block of code is being repeated at various places can we do something like this instead? 
```suggestion
static __always_inline int is_dev_shm(char *name , char *is_path) {
```

2024-12-23 11:00 UTC, Aryan-sharma11 commented on KubeArmor/presets/protectEnv/preset.go
> +}
these functions are doing nothing

2024-12-23 11:32 UTC, rksharma95 commented on KubeArmor/feeder/feeder.go
> +		kg.Printf("PRESET LOG 2: %+v\n", log)
it's just a debug log, forgot to remove it. thanks for catch!

2024-12-23 11:34 UTC, rksharma95 commented on KubeArmor/presets/protectEnv/preset.go
> +}
protect env is not being handled with this PR i will comment TODO. and let's handle it with another PR.

2024-12-24 12:17 UTC, Aryan-sharma11 submitted a review, later dismissed

2025-01-02 06:08 UTC, Aryan-sharma11 approved these changes

2025-01-08 12:27 UTC, daemon1024 reviewed
LGTM

2025-01-09 18:58 UTC, rootxrishabh approved these changes

2025-01-10 11:40 UTC, merged