feat(deployment): Enhance Docker ImagePull Secrets Configuration
kubearmor/KubeArmor pull request #1754
Opened 2024-05-15 10:33 UTC by janavenkat

In larger production environments, we may get rate-limited by Docker Hub for a lot of image pulls. So, I've added an option for providing the Docker pull secret name to avoid rate limits.

**Purpose of PR?**:

Add option for passing docker pull secrets in helm template

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered::
Using helm template 

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [X] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2024-05-21 07:04 UTC, rksharma95 commented
@janavenkat thanks for the PR, Lets extend the imagePullSecret configuration to operator deployment model as well. Let me know if anything is needed from my side.

2024-05-23 07:37 UTC, janavenkat commented
> @janavenkat thanks for the PR, Lets extend the imagePullSecret configuration to operator deployment model as well. Let me know if anything is needed from my side.

Sure will add changes for operator as well.

2024-07-15 14:37 UTC, janavenkat commented
> @janavenkat thanks for the PR, Lets extend the imagePullSecret configuration to operator deployment model as well. Let me know if anything is needed from my side.

Added for Operator as well

2024-07-15 17:34 UTC, nyrahul commented
@rksharma95 @daemon1024 , can you please review this PR? Thanks

2024-07-18 06:57 UTC, rksharma95 submitted a review, later dismissed
@janavenkat changes looks good assuming that [kubearmor helm chart](https://github.com/kubearmor/KubeArmor/tree/main/deployments/helm/KubeArmor) is being used to deploy.

operator uses [get pkg](https://github.com/kubearmor/KubeArmor/tree/main/deployments/get) to generate kubearmor resources and it will require to add this change there to be in effect.

we've a in-progress action item of major refactoring of kubearmor-operator https://github.com/kubearmor/KubeArmor/issues/1779 we can take care of this feature request as part of it. thanks for your suggestion

2024-10-25 14:18 UTC, janavenkat commented
@rksharma95 @daemon1024 can we merge this PR?

2024-11-04 06:37 UTC, daemon1024 approved these changes, later dismissed

2024-12-23 22:44 UTC, Prateeknandle requested changes
please remove default tolerations present in daemonset, which make kubearmor available in tainted nodes, without explicitly adding toleration for them.

default toleration is:
```
      tolerations:
      - operator: Exists

```

2024-12-25 23:54 UTC, Prateeknandle reviewed
Initially when we define `globalTolerations` and `globalImagePullSecrets` through kubearmorconfig it is not reflected in deployments or daemonset, after some update in config when we again apply it, then it is getting reflected.

After reflecting the changes in deployments and daemonset, I've seen expected behaviour.

Kindly look into this as well.

2025-01-06 11:10 UTC, Prateeknandle approved these changes, later dismissed
LGTM, please fix the ci

2025-01-06 11:56 UTC, Prateeknandle reviewed
Please take a look at the ci changes, one test is failing constantly while running kubearmor.

2025-01-07 10:30 UTC, Prateeknandle approved these changes

2025-01-07 18:34 UTC, daemon1024 approved these changes

2025-01-07 18:35 UTC, daemon1024 approved these changes

2025-01-07 18:35 UTC, merged