feat: Add support for containerd hooks
kubearmor/KubeArmor pull request #1763
Opened 2024-05-22 22:28 UTC by AbdelrahmanElawady

**Purpose of PR?**:
Support running KubeArmor with containerd using OCI hooks. It need NRI to be enabled on the cluster and [hook-injector](https://github.com/containerd/nri/tree/main/plugins/hook-injector) plugin to be running.

**Does this PR introduce a breaking change?**

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

Just the getting started example.

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2025-02-06 08:06 UTC, rootxrishabh commented
NRI was added in [1674](https://github.com/kubearmor/KubeArmor/pull/1674)

2025-07-02 18:17 UTC, rksharma95 reviewed
@AbdelrahmanElawady can you provide a diagram that explains the design in detail?

2025-07-02 18:17 UTC, rksharma95 commented on pkg/KubeArmorOperator/hook/main.go
> +func run(state specs.State) error {
need some explanation to understand this, looking for answer of a few questions:
- what's this detached process?
- why it need kubearmor information.

2025-07-02 18:17 UTC, rksharma95 commented on pkg/KubeArmorOperator/cmd/snitch-cmd/main.go
> +		if err := applyCRIOHook(socket); err != nil {
just to confirm, it's genric way to check OCI hook support for any CRI not limited to cri-o right!

2025-07-03 21:39 UTC, rootxrishabh commented on pkg/KubeArmorOperator/cmd/snitch-cmd/main.go
> +		if err := applyCRIOHook(socket); err != nil {
@rksharma95, I think this was done as NRI support for containerd was not available at the time this PR was created. CRI-O supports hooks out of the box.

2025-07-03 21:45 UTC, rootxrishabh commented on pkg/KubeArmorOperator/hook/main.go
> +func run(state specs.State) error {
@rksharma95, detached process is when hook actually starts before kubearmor. Ka.sock is owned by kubearmor and hook waits for socket to start. Needs kubearmor information to know when kubearmor starts.

2025-07-09 07:31 UTC, rksharma95 commented on pkg/KubeArmorOperator/cmd/snitch-cmd/main.go
> +		if err := applyCRIOHook(socket); err != nil {
so do we need to handle anything here?

2025-07-13 10:16 UTC, rootxrishabh commented on pkg/KubeArmorOperator/hook/main.go
> +	} else {
@AbdelrahmanElawady else would trigger in case receive an error while reading config.json?
If yes, then should we expect to read `specBytes` on line 157.

2025-07-13 10:23 UTC, AbdelrahmanElawady commented on pkg/KubeArmorOperator/hook/main.go
> +	} else {
else would run if err == nil. error handling is done in line 147

2025-07-13 10:28 UTC, rootxrishabh commented on pkg/KubeArmorOperator/hook/main.go
> +	} else {
oops my bad, thanks for the clarification 🙌

2025-07-13 10:44 UTC, rootxrishabh commented
@AbdelrahmanElawady, looking at the hook binary. I think we stop depending on hook stdin and call runtime socket for container info after kubearmor starts. I am not sure whats the logic here. Can you please explain?

2025-07-13 15:03 UTC, AbdelrahmanElawady commented
@rootxrishabh it's been a while so might not remember correctly but I think we use stdin to figure out container id, status, pid and the bundle path which are all part of the [state](https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#state) object sent in stdin. this is according to OCI spec as mentioned [here](https://github.com/opencontainers/runtime-spec/blob/main/config.md#posix-platform-hooks).
> The [state](https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#state) of the container MUST be passed to hooks over stdin so that they may do work appropriate to the current state of the container.

We call runtime socket for previous containers but this is separate than hook stdin

2025-07-15 10:19 UTC, rksharma95 requested changes

2025-07-15 10:19 UTC, rksharma95 commented on pkg/KubeArmorOperator/cmd/snitch-cmd/main.go
> +	hookDir := "/usr/share/containers/oci/hooks.d/"
in case of containerd it should be `/etc/containers/oci/hooks.d` 

how it will be handled? should we support a flag with operator to accept this path as we also need to mount this path with snitch, it will be an issue if we dynamically support multiple paths.

2025-07-15 10:19 UTC, rksharma95 commented on pkg/KubeArmorOperator/internal/controller/resources.go
> +							{
snitch has a command line flag as well to enable OCI Hook, let's handle that as well.

2025-07-15 18:25 UTC, rootxrishabh commented on pkg/KubeArmorOperator/cmd/snitch-cmd/main.go
> +	hookDir := "/usr/share/containers/oci/hooks.d/"
We can auto set this path under the condition of which runtime socket is detected. Right?

2025-07-16 03:41 UTC, rksharma95 commented on pkg/KubeArmorOperator/cmd/snitch-cmd/main.go
> +	hookDir := "/usr/share/containers/oci/hooks.d/"
this is what I'm concerned with, it will need mounting all possible path with the snitch and if that not exist snitch will be reconciled again after that mount points handled.

2025-07-16 19:02 UTC, rootxrishabh commented on pkg/KubeArmorOperator/cmd/snitch-cmd/main.go
> +	hookDir := "/usr/share/containers/oci/hooks.d/"
CRI-O also supports `/etc/containers/oci/hooks.d/` as a path for hook configuration. I think we can use this for both crio and containerd.

2025-07-23 16:33 UTC, rksharma95 commented on pkg/KubeArmorOperator/internal/controller/resources.go
> +							{
this is not being handled as of now.

2025-07-24 10:06 UTC, rootxrishabh submitted a review, later dismissed
LGTM 🚀 

Great work @AbdelrahmanElawady !

2025-07-24 12:23 UTC, rootxrishabh approved these changes

2025-07-24 12:29 UTC, rksharma95 approved these changes

2025-07-24 12:30 UTC, Aryan-sharma11 approved these changes

2025-07-24 12:30 UTC, merged

2025-07-24 12:31 UTC, rksharma95 commented
PR tested locally on both containerd and crio setup. CI is failing due to docker pull limits and few tests are flaky.