test(test): Adding fuzzer for ContainerPolicy
kubearmor/KubeArmor pull request #1797
Opened 2024-07-07 15:59 UTC by prady0t

**Purpose of PR?**:

This is a fuzzer for `ContainerPolicy` https://github.com/kubearmor/KubeArmor/blob/a5f584c38ee7cd674d1e95a3f7ce7842212dfe12/KubeArmor/policy/policy.go#L24

For seed corpus I referred to [this](https://docs.kubearmor.io/kubearmor/documentation/security_policy_examples#:~:text=Block%20a%20specific%20executable) policy and removed `Metadata.Name` from it. 
With this we are testing if invalid policy results in `PolicyStatus_Invalid` or not. 
To run the fuzz test, 

```
cd KubeArmor/policy
go test -fuzz=Fuzz
```
Addresses #1367 

**Does this PR introduce a breaking change?**
NO

2024-07-10 06:49 UTC, prady0t commented
Already found an issue with this. I ran the fuzzer for a while and It failed for this input : 
```json
{
    "0000": "00000000000000",
    "oBjeCt": {
        "metAdAtA": {
            "nAme": "0"
        }
    }
}
```
Which is totally understandable. To fix this we can also have a condition in fuzzer to check for status as `Applied` if we have `policyEvent.Object.Metadata.Name != ""` . Here's the log : 

```
--- FAIL: FuzzContainerPolicy (0.00s)
    --- FAIL: FuzzContainerPolicy/69798181ccc6962d (0.00s)
        ContainerPoilcy_fuzz_test.go:58: Unexpected status: Applied, [123 32 32 32 32 34 48 48 48 48 34 58 32 34 48 48 48 48 48 48 48 48 48 48 48 48 48 48 34 44 32 32 32 32 34 111 66 106 101 67 116 34 58 32 123 32 32 32 32 32 34 109 101 116 65 100 65 116 65 34 58 32 123 32 32 32 32 32 32 34 110 65 109 101 34 58 32 34 48 34 125 125 125]
FAIL
exit status 1
FAIL    github.com/kubearmor/KubeArmor/KubeArmor/policy 0.011s
```

2024-07-26 17:39 UTC, prady0t commented
I've added a check for `pb.PolicyStatus_Applied` as well for JSON inputs with `Object.Metadata.Name != ""`. With this, our fuzzer should run until it finds an edge case where input results in `Unexpected Status`. We could have also added a condition to check if we get a `pb.PolicyStatus_Applied` status when `Object.Metadata.Name != ""` inside the fuzzer itself, instead of just the AND condition. But that would require to unmarshal the `data` and would be kind of meta (testing json.Unmarshal with json.Unmarshal).

If you think it's testing something useful, we can go ahead and merge it. Once we have this inside KubeArmor codebase, we can try writing config files so that we can integrate it with oss-fuzz. Running it locally won't give much fruitful results. 
In the [cilium fuzz testing report](https://docs.cilium.io/en/stable/_downloads/1bca8c3d8bb912f689017e7092afe682/CiliumFuzzingAudit2022.pdf) (mentioned in the upstream issue comments), we can see fuzzers run for 1000s of hours : 

<img width="751" alt="Screenshot 2024-07-26 at 10 59 30 PM" src="https://github.com/user-attachments/assets/6c706208-0ecf-4912-889c-9d16e9784af2">

Running our fuzzers with oss fuzz will help us improve it even better. We may also find some crucial bugs. This could be a starting point for how we can add more fuzzer. 

@daemon1024 @DelusionalOptimist Do let me know what you guys think of this.

2024-08-07 18:00 UTC, nyrahul requested changes
Thank you for the PR

2024-08-07 18:00 UTC, nyrahul commented on KubeArmor/policy/ContainerPoilcy_fuzz_test.go
Please fix the filename spelling .. Poilcy => Policy

2024-08-07 18:00 UTC, nyrahul commented on KubeArmor/policy/ContainerPoilcy_fuzz_test.go
> +package policy
Please add the SPDX header needed in all code files.

2024-08-07 18:13 UTC, nyrahul commented
I think this PR and the resultant image could be uses as input for OSS-Fuzz. How long did you test it on your local system? @prady0t

2024-08-07 18:13 UTC, nyrahul requested changes

2024-08-07 18:13 UTC, nyrahul commented on KubeArmor/policy/ContainerPoilcy_fuzz_test.go
> +	tp "github.com/kubearmor/KubeArmor/KubeArmor/types"
```suggestion
	pb "github.com/kubearmor/KubeArmor/protobuf"
	tp "github.com/kubearmor/KubeArmor/KubeArmor/types"
```

2024-08-08 04:22 UTC, prady0t commented
> I think this PR and the resultant image could be uses as input for OSS-Fuzz. How long did you test it on your local system? @prady0t

For about an hour. Do you want me to run it overnight? It might help us find any early bug or any problems with the fuzzer.

2024-08-10 19:00 UTC, nyrahul commented
Running it in current state won't result in anything since the primary function is stubbed out.

2024-08-10 19:15 UTC, nyrahul commented
The primary updates I made using the last commit is:

* Using the real `ParseAndUpdateContainerSecurityPolicy` to fuzz test. Removed the stubbed UpdateContainerPolicy.
* Fixing the fuzz test initial data

This is already showing up some issues during fuzz ... We need to check if those are genuine issues or need stubbing.

2024-08-10 21:36 UTC, prady0t commented
Thanks a Lot for these changes! This makes much more sense now. Let me try to run these locally

2024-08-22 11:31 UTC, prady0t commented
Sorry for the late reply. Fuzzer is failing for this input : 
```
[]byte("{\"oBjeCt\":{\"metAdAtA\":{\"nAme\":\"0\"},\"speC\":{\"seleCtor\":{\"mAtChLABels\":{\"\":\"\"}}}}}")

```

2024-09-29 05:28 UTC, prady0t commented
The fuzzer is now running. Would like your reviews @nyrahul @daemon1024 @DelusionalOptimist

2024-09-30 11:13 UTC, daemon1024 requested changes

2024-09-30 11:13 UTC, daemon1024 commented on KubeArmor/core/containerPolicy_fuzz_test.go
> +		Policy: []byte(`
Let's use varied kinds of policy including file, network as seed values. https://github.com/kubearmor/KubeArmor/tree/main/tests/k8s_env/ksp/multiubuntu

2024-09-30 11:13 UTC, daemon1024 commented on KubeArmor/core/unorchestratedUpdates.go
> +					// delete endpoint if no containers or policies
We already found a bug and fixed it, Nice 🔥

2024-10-14 06:26 UTC, daemon1024 commented
@prady0t https://github.com/kubearmor/KubeArmor/actions/runs/11170637360/job/31168314822?pr=1797
gofmt fails ( even though the CI is passing ). Please run the formatter

2024-10-15 05:47 UTC, DelusionalOptimist requested changes
@prady0t looks mostly good. One small fix.
Also, can you squash the commits?

2024-10-15 05:47 UTC, DelusionalOptimist commented on KubeArmor/core/unorchestratedUpdates.go
> +		if endpointIdx != -1 {
```suggestion
		if endpointIdx >= 0 {
```

2024-10-15 13:47 UTC, closed without merging