Enabling BPFLSM based KSP protection on Kubearmor itself
kubearmor/KubeArmor pull request #1831
Opened 2024-08-07 09:21 UTC by daemon1024

**Purpose of PR?**:

Succeeds #1717

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2024-10-24 06:46 UTC, rksharma95 approved these changes, later dismissed
LGTM :+1:

2024-10-24 13:16 UTC, Aryan-sharma11 requested changes
lets use `filepath.Join()` to build paths.

2024-10-24 13:16 UTC, Aryan-sharma11 commented on KubeArmor/core/containerdHandler.go
> +		if data, err := os.Readlink(cfg.GlobalCfg.ProcFsMount + "/" + pid + "/ns/pid"); err == nil {
```suggestion
		if data, err :=os.Readlink(filepath.Join(cfg.GlobalCfg.ProcFsMount, pid, "ns/pid")); err == nil {
```

2024-10-24 13:16 UTC, Aryan-sharma11 commented on KubeArmor/core/containerdHandler.go
> +		if data, err := os.Readlink(cfg.GlobalCfg.ProcFsMount + "/" + pid + "/ns/mnt"); err == nil {
```suggestion
		if data, err := os.Readlink(filepath.Join(cfg.GlobalCfg.ProcFsMount, pid, "ns/pid")); err == nil {
```

2024-10-24 13:16 UTC, Aryan-sharma11 commented on KubeArmor/core/crioHandler.go
> +	if data, err := os.Readlink(cfg.GlobalCfg.ProcFsMount + "/" + pid + "/ns/pid"); err == nil {
```suggestion
	if data, err := os.Readlink(filepath.Join(cfg.GlobalCfg.ProcFsMount, pid, "ns/pid")); err == nil{
```

2024-10-24 13:16 UTC, Aryan-sharma11 commented on KubeArmor/core/crioHandler.go
> +	if data, err := os.Readlink(cfg.GlobalCfg.ProcFsMount + "/" + pid + "/ns/mnt"); err == nil {
```suggestion
	if data, err := os.Readlink( filepath.Join(cfg.GlobalCfg.ProcFsMount , pid , "/ns/mnt")); err == nil {
```

2024-10-24 13:16 UTC, Aryan-sharma11 commented on KubeArmor/core/dockerHandler.go
> +	if data, err := os.Readlink(cfg.GlobalCfg.ProcFsMount + "/" + pid + "/ns/pid"); err == nil {
```suggestion
	if data, err := os.Readlink(filepath.Join(cfg.GlobalCfg.ProcFsMount, pid ,"/ns/pid")); err == nil {
```

2024-10-30 18:38 UTC, Aryan-sharma11 approved these changes

2024-11-05 04:34 UTC, rootxrishabh approved these changes
LGTM :+1:

2024-11-05 06:08 UTC, merged