refactor(operator): remove config empty check
kubearmor/KubeArmor pull request #1841
Opened 2024-08-14 17:10 UTC by carlosrodfern

The config elements, though optional, are not ptr, so they are initialized with the respective type default values. As result, strconv.Format... will never return an empty string, so the check is unnecessary. I also found that the setting of ThrottleSec was depending on MaxAlertPerSec, but because that one is never empty, the dependency wasn't actually effective anyways.

**Purpose of PR?**:

Clean up

**Does this PR introduce a breaking change?** No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :

I stumbled with this code while troubleshooting something else. This is a clean up and doesn't impact existing logic.

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2024-08-19 17:49 UTC, carlosrodfern commented
I'm unable to see why `ci-test-ginkgo` failed with this change. Any idea I can work on?

2024-08-20 13:18 UTC, DelusionalOptimist commented
> I'm unable to see why `ci-test-ginkgo` failed with this change. Any idea I can work on?
> 
> What I see is that it is expecting an alert to show up, but the logs simply post: `time="2024-08-15T20:14:22Z" level=info msg="event timeout"`

@carlosrodfern yeah... The failure isn't relevant. Tests are a little flakey on the GitHub runners.
`event timeout` indicates that it was trying to look for a matching alert on the gRPC stream that is created for getting alerts from KubeArmor but it didn't find one. These scenarios pass when run locally or on our self hosted runners but due to some performance issues fail on GitHub runners. We have tried doing multiple things in the past but haven't had much success in making the tests less flakier.

2024-09-12 09:50 UTC, daemon1024 requested changes

2024-09-12 09:50 UTC, daemon1024 commented on pkg/KubeArmorOperator/internal/controller/cluster.go
>  	}
```suggestion
	if config.MaxAlertPerSec == 0 {
                        MaxAlertPerSec = common.DefaultMaxAlertPerSec
	} 
	if common.ConfigMapData[common.ConfigMaxAlertPerSec] != MaxAlertPerSec {
			common.ConfigMapData[common.ConfigMaxAlertPerSec] = MaxAlertPerSec
			updated = true
	}
```

2024-09-12 11:29 UTC, daemon1024 approved these changes

2024-09-13 05:15 UTC, rksharma95 approved these changes

2024-09-17 06:21 UTC, merged