feat : process arguments matching
kubearmor/KubeArmor pull request #1869
Opened 2024-10-03 08:04 UTC by Aryan-sharma11

**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

2024-10-14 08:32 UTC, Aryan-sharma11 commented on KubeArmor/BPF/common.h
> +struct argVal{
need to discuss on length and number of arguments that should be stored per command

2024-11-12 17:50 UTC, rootxrishabh commented
BPFLSM enforcer not starting, here's the error message -

`
2024-11-12 10:39:53.824274	ERROR	error creating kubearmor_arguments_map: creating map: map create: argument list too long (without BTF k/v)
github.com/kubearmor/KubeArmor/KubeArmor/log.Err
	/usr/src/KubeArmor/KubeArmor/log/logger.go:103
github.com/kubearmor/KubeArmor/KubeArmor/feeder.(*Feeder).Errf
	/usr/src/KubeArmor/KubeArmor/feeder/feeder.go:446
github.com/kubearmor/KubeArmor/KubeArmor/enforcer/bpflsm.NewBPFEnforcer
	/usr/src/KubeArmor/KubeArmor/enforcer/bpflsm/enforcer.go:111
github.com/kubearmor/KubeArmor/KubeArmor/enforcer.selectLsm
	/usr/src/KubeArmor/KubeArmor/enforcer/runtimeEnforcer.go:106
github.com/kubearmor/KubeArmor/KubeArmor/enforcer.NewRuntimeEnforcer
	/usr/src/KubeArmor/KubeArmor/enforcer/runtimeEnforcer.go:175
github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).InitRuntimeEnforcer
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:292
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:548
main.main
	/usr/src/KubeArmor/KubeArmor/main.go:79
runtime.main
	/usr/local/go/src/runtime/proc.go:271
2024-11-12 10:39:53.824329	INFO	Error Initialising BPF-LSM Enforcer, Cleaning Up
`

Environment - 
 - K8s -> EKS
 - Container Runtime -> containerd://1.7.22
 - Kernel Version -> 5.10.227-219.884.amzn2.x86_64
 - Operating system -> Amazon Linux 2

2024-11-12 17:50 UTC, rootxrishabh reviewed
BPFLSM enforcer not starting, here's the error message -

`
2024-11-12 10:39:53.824274	ERROR	error creating kubearmor_arguments_map: creating map: map create: argument list too long (without BTF k/v)
github.com/kubearmor/KubeArmor/KubeArmor/log.Err
	/usr/src/KubeArmor/KubeArmor/log/logger.go:103
github.com/kubearmor/KubeArmor/KubeArmor/feeder.(*Feeder).Errf
	/usr/src/KubeArmor/KubeArmor/feeder/feeder.go:446
github.com/kubearmor/KubeArmor/KubeArmor/enforcer/bpflsm.NewBPFEnforcer
	/usr/src/KubeArmor/KubeArmor/enforcer/bpflsm/enforcer.go:111
github.com/kubearmor/KubeArmor/KubeArmor/enforcer.selectLsm
	/usr/src/KubeArmor/KubeArmor/enforcer/runtimeEnforcer.go:106
github.com/kubearmor/KubeArmor/KubeArmor/enforcer.NewRuntimeEnforcer
	/usr/src/KubeArmor/KubeArmor/enforcer/runtimeEnforcer.go:175
github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).InitRuntimeEnforcer
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:292
github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
	/usr/src/KubeArmor/KubeArmor/core/kubeArmor.go:548
main.main
	/usr/src/KubeArmor/KubeArmor/main.go:79
runtime.main
	/usr/local/go/src/runtime/proc.go:271
2024-11-12 10:39:53.824329	INFO	Error Initialising BPF-LSM Enforcer, Cleaning Up
`

Environment - 
 - K8s -> EKS
 - Container Runtime -> containerd://1.7.22
 - Kernel Version -> 5.10.227-219.884.amzn2.x86_64
 - Operating system -> Amazon Linux 2

2025-06-23 05:39 UTC, rootxrishabh submitted a review, later dismissed

2025-06-24 04:33 UTC, rksharma95 reviewed
please format ebpf code for readability.

2025-06-24 04:33 UTC, rksharma95 commented on KubeArmor/BPF/shared.h
> +      for( u8 i = 0 ; i< num_of_args && i <= 16; i++ ){
can you re-format the code?

2025-06-24 04:33 UTC, rksharma95 commented on KubeArmor/BPF/system_monitor.c
> +          {
same here.

2025-06-24 04:33 UTC, rksharma95 commented on KubeArmor/BPF/system_monitor.c
> +    // add number of args here // pragmaunroll
directive is commented. is this intended?

2025-06-25 16:52 UTC, rksharma95 requested changes

2025-06-25 16:52 UTC, rksharma95 commented on KubeArmor/BPF/common.h
> +#define MAX_STR_ARR_ELEM 20
is it supposed to be 16? we have max num of args defined as 16 with arg matching.

2025-06-25 16:52 UTC, rksharma95 commented on KubeArmor/BPF/common.h
> +#define MAX_ARGUMENT_SIZE 256
`MAX_ARGUMENT_SIZE` is not being used.

2025-06-25 16:52 UTC, rksharma95 commented on pkg/KubeArmorController/api/security.kubearmor.com/v1/common.go
> +	AllowedArgs []string `json:"allowedArgs,omitempty"`
as we're handling fixed max length argument with matcher, we can add constraint of max arg length 80 by creating a type for arg string.

2025-07-03 09:51 UTC, rksharma95 commented
<details>

<summary> karmor probe</summary>

```
Found KubeArmor running in Kubernetes

Daemonset :
 	kubearmor 	Desired: 1	Ready: 1	Available: 1	
Deployments : 
 	kubearmor-controller	Desired: 1	Ready: 1	Available: 1	
 	kubearmor-operator  	Desired: 1	Ready: 1	Available: 1	
 	kubearmor-relay     	Desired: 1	Ready: 1	Available: 1	
Containers : 
 	kubearmor-bpf-containerd-2c350-zc6dq	Running: 1	Image Version: aryan1126/kubearmor                    	
 	kubearmor-controller-578b8658c-7r8xs	Running: 1	Image Version: kubearmor/kubearmor-controller:latest  	
 	kubearmor-operator-584bf64984-h2x6z 	Running: 1	Image Version: aryan1126/kubearmor-operator:latest    	
 	kubearmor-relay-fb966b895-45slq     	Running: 1	Image Version: kubearmor/kubearmor-relay-server:latest	
Node 1 : 
 	OS Image:                 	Arch Linux              	
 	Kernel Version:           	6.12.24-1-lts           	
 	Kubelet Version:          	v1.31.5+k3s1            	
 	Container Runtime:        	containerd://1.7.23-k3s2	
 	Active LSM:               	BPFLSM                  	
 	Host Security:            	false                   	
 	Container Security:       	true                    	
 	Container Default Posture:	audit(File)             	audit(Capabilities)	audit(Network)	
 	Host Default Posture:     	audit(File)             	audit(Capabilities)	audit(Network)	
```

</details>
 	
---

<details>

<summary>Scenario 1: without any policy </summary>

```
❯ kubectl get ksp
No resources found in default namespace.
❯ kubectl get csp
No resources found

❯ kubectl top pod -n kubearmor                           
NAME                                   CPU(cores)   MEMORY(bytes)
kubearmor-bpf-containerd-2c350-qfbqc   17m          235Mi
kubearmor-controller-578b8658c-7r8xs   1m           24Mi
kubearmor-operator-584bf64984-h2x6z    3m           18Mi
kubearmor-relay-fb966b895-45slq        18m          24Mi
```

</details>



---

<details>

<summary>Scenario 2: 1 ksp targeting a single pod </summary>

```
❯ kubectl get ksp
NAME                   AGE
allow-steampipe-args   2m41s

❯ kubectl get csp
No resources found

❯ kubectl top pod -n kubearmor  
NAME                                   CPU(cores)   MEMORY(bytes)
kubearmor-bpf-containerd-2c350-qfbqc   18m          238Mi
kubearmor-controller-578b8658c-7r8xs   1m           24Mi
kubearmor-operator-584bf64984-h2x6z    2m           17Mi
kubearmor-relay-fb966b895-45slq        18m          24Mi

❯ kubectl exec -it python-deployment-5c68bd744d-m6fs8 -- bash
root@python-deployment-5c68bd744d-m6fs8:/# python http.server
bash: /usr/local/bin/python: Permission denied
root@python-deployment-5c68bd744d-m6fs8:/# python modules.steampipe_aws
python: can't open file '//modules.steampipe_aws': [Errno 2] No such file or directory

== Alert / 2025-07-03 09:25:56.421781 ==
ClusterName: default
HostName: archlinux
NamespaceName: default
PodName: python-deployment-5c68bd744d-m6fs8
Labels: app=python
ContainerName: python
ContainerID: aae4e219c6a7ee1268ed4c18e58d37c8c9d20bfd42efd7b81b60e4919d119e30
ContainerImage: docker.io/library/python:3.10-slim@sha256:9dd6774a1276178f94b0cc1fb1f0edd980825d0ea7634847af9940b1b6273c13
Type: MatchedPolicy
PolicyName: allow-steampipe-args
Source: /usr/bin/bash
Resource: /usr/local/bin/python3.10 http.server
Operation: Process
Action: Block
Data: lsm=SECURITY_BPRM_CHECK
Enforcer: BPFLSM
Result: Permission denied
Cwd: /
HostPID: 523461
HostPPID: 523246
Owner: map[Name:python-deployment Namespace:default Ref:Deployment]
PID: 52
PPID: 523246
ParentProcessName: /usr/bin/bash
ProcessName: /usr/local/bin/python3.10
TTY: pts0
UID: 0
```

</details>



---

<details>

<summary>Scenario 3: A csp targeting all namsepaces </summary>

```
# total no of pods
❯ kubectl get pods -A | grep -v NAMESPACE | wc -l
33
❯ kubectl get ksp -A
No resources found
❯ kubectl get csp
NAME                   AGE
allow-steampipe-args   105s

❯ kubectl top pod -n kubearmor  
NAME                                   CPU(cores)   MEMORY(bytes)
kubearmor-bpf-containerd-2c350-qfbqc   18m          241Mi
kubearmor-controller-578b8658c-7r8xs   1m           25Mi
kubearmor-operator-584bf64984-h2x6z    4m           18Mi
kubearmor-relay-fb966b895-45slq        21m          26Mi
```

</details>



---

<details>

<summary>Scenario 4: added 50 more pods</summary>

```
❯ kubectl scale deployment python-deployment --replicas=50
deployment.apps/python-deployment scaled
❯ kubectl get pods -l app=python | grep Running | wc -l
50

❯ kubectl top pod -n kubearmor  
NAME                                   CPU(cores)   MEMORY(bytes)
kubearmor-bpf-containerd-2c350-qfbqc   30m          303Mi
kubearmor-controller-578b8658c-7r8xs   2m           27Mi
kubearmor-operator-584bf64984-h2x6z    2m           17Mi
kubearmor-relay-fb966b895-45slq        16m          28Mi
```

</details>



---

<details>

<summary>Scenario 5: added 80 more pods</summary>

```
❯ kubectl scale deployment python-deployment --replicas=80
deployment.apps/python-deployment scaled

❯ kubectl get pods -l app=python | grep Running | wc -l
80

NAME                                   CPU(cores)   MEMORY(bytes)
kubearmor-bpf-containerd-2c350-qfbqc   34m          344Mi
kubearmor-controller-578b8658c-7r8xs   1m           28Mi
kubearmor-operator-584bf64984-h2x6z    4m           19Mi
kubearmor-relay-fb966b895-45slq        16m          29Mi

NAME                                   CPU(cores)   MEMORY(bytes)
kubearmor-bpf-containerd-2c350-qfbqc   29m          308Mi
kubearmor-controller-578b8658c-7r8xs   2m           26Mi
kubearmor-operator-584bf64984-h2x6z    3m           19Mi
kubearmor-relay-fb966b895-45slq        15m          29Mi
```

</details>

2025-07-03 09:53 UTC, rksharma95 submitted a review, later dismissed
LGTM :rocket: 
nice job @Aryan-sharma11 :ok_hand:

2025-07-03 11:01 UTC, rksharma95 commented
@Aryan-sharma11 please squash the commits.

2025-07-04 08:45 UTC, rootxrishabh submitted a review, later dismissed

2025-07-09 07:02 UTC, rksharma95 approved these changes
tested with clang version 19.1.7 as well. :+1:

2025-07-09 07:18 UTC, rootxrishabh approved these changes

2025-07-09 07:40 UTC, merged