Adding fuzzer for HostPolicy
kubearmor/KubeArmor pull request #1872
Opened 2024-10-12 11:34 UTC by prady0t

**Purpose of PR?**:

This is a fuzzer for `HostPolicy` https://github.com/kubearmor/KubeArmor/blob/a5f584c38ee7cd674d1e95a3f7ce7842212dfe12/KubeArmor/policy/policy.go#L52

For seed corpus I referred to [this](https://github.com/kubearmor/policy-templates/blob/d4c0129eeaee43fb6a7e9b93060e29022a1e7477/cve/system/hsp-cve-2019-14271.yaml#L6)  
To run the fuzz test, 

```
cd KubeArmor/policy
go test -fuzz=Fuzz
```
Addresses #1367 

**Does this PR introduce a breaking change?**
NO

2024-10-12 11:39 UTC, prady0t commented
@daemon1024 @DelusionalOptimist @Prateeknandle This fuzzer works fine and no changes to the codebase were required. Please have a look

2024-10-15 05:48 UTC, DelusionalOptimist requested changes
Please squash your commits here as well.

2024-10-15 05:48 UTC, DelusionalOptimist commented on KubeArmor/core/testdata/fuzz/FuzzContainerPolicy/bb2a6f290a615f3e
Is this file needed?

2024-10-16 07:31 UTC, DelusionalOptimist approved these changes

2024-10-16 07:36 UTC, daemon1024 approved these changes

2024-10-16 10:56 UTC, merged