feat(core): handle sctp protocol and all protocols with raw socket and add protocol:all network rule
kubearmor/KubeArmor pull request #1892
Opened 2024-11-12 11:52 UTC by rksharma95

**Purpose of PR?**:
this PR adds changes to handle:
- sctp protocol rule
- all protocols with raw network socket/domain
and adds support to handle `protocol: all` rule for network rules
```yaml
action: Block
network:
  matchProtocols:
  -  protocol: all
```
Fixes #1838 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #1838
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [x] Commit has integration tests

2025-01-08 06:57 UTC, Aryan-sharma11 requested changes

2025-01-08 06:57 UTC, Aryan-sharma11 commented on KubeArmor/BPF/enforcer.bpf.c
> +   bpf_printk("type: %d protocol: %d", type, protocol);
remove this

2025-01-08 07:11 UTC, Aryan-sharma11 commented
Tested on EKS 2 node cluster, working as expected.

2025-01-09 19:24 UTC, daemon1024 approved these changes, later dismissed
LGTM 👌🏽

2025-01-10 13:03 UTC, daemon1024 commented
@rksharma95 can you rebase and rebuild object files to resolve conflicts?

2025-01-11 06:21 UTC, daemon1024 approved these changes

2025-01-12 11:22 UTC, Aryan-sharma11 approved these changes

2025-01-12 11:49 UTC, merged