KVM Agent - Prepare the build framework and basic structure for the service
kubearmor/KubeArmor pull request #375
Opened 2021-09-19 05:36 UTC by seswarrajan

2021-09-29 05:11 UTC, nyrahul requested changes
Please check inline comments. Thanks

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +			kg.Printf("Failed to initialize KvmAgent. Err : %s\n", err)
Please use an error print here

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +	return (os.Getenv("CLUSTER_IP") + ":" + os.Getenv("CLUSTER_PORT"))
Best to use `net.JoinHostPort`. This will take care of IPv6 address handling as well.

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +		log.Print("Unmarshal error => ", err)
This should be a error print.

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +	} else {
Better to return in case of error with err.

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +		grpcClientConn.Close()
Use defer grpcClientConn.Close() in the beginning of the function. The best would be to use defer in the function that created this connection.

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +			log.Printf("Error %s ", err)
Need error print

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +			log.Print("Policy Enforcement failed")
Need error print

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +
Please have a log here on in the defer function as proposed above to indicate this connection closure.

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +	err = nil
Is there a need for this `err = nil`?

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +		log.Print("Failed to connect to server")
error print needed

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +		err = errors.New("Invalid Client connection")
do not use capital letters in error string. Typical guideline to follow across all error response. In general, it is best not to use capitalized strings unless it is an abbreviation.

2021-09-29 05:11 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +		log.Printf("Failed to register identity %d", response.Status)
need error print

2021-10-26 02:39 UTC, nyrahul requested changes
I think closing the grpc connection handling still has issues. @seswarrajan , can you check the new comment? Thanks

2021-10-26 02:39 UTC, nyrahul commented on KubeArmor/kvmAgent/kvmAgent.go
> +			syscall.Kill(syscall.Getpid(), syscall.SIGINT)
In this condition `grpcClientConn.Close()` is not done! Can we simply use defer for closing it?

2021-10-26 06:56 UTC, seswarrajan commented on KubeArmor/kvmAgent/kvmAgent.go
> +			syscall.Kill(syscall.Getpid(), syscall.SIGINT)
When we use defer for closing grpcConnection, we faced an issue. The connection is closing even before use. I will test the solution and will update you on the same.

2021-11-15 06:27 UTC, merged