WIP: Event auditor codegen - initial commit
kubearmor/KubeArmor pull request #381
Opened 2021-09-20 16:27 UTC by johngv2

initial commit

2021-10-06 12:24 UTC, geyslan approved these changes
@johngv2 I've dropped a few words for discussion.

2021-10-06 12:24 UTC, geyslan commented on KubeArmor/BPF/codegen.bpf.h
> +}
What do you think to put part of this "get task info" logic inside `shared.h` (this file can be renamed to common.h). This would make possible its reuse for many bpf programs to come.

2021-10-06 12:24 UTC, geyslan commented on KubeArmor/BPF/maps.bpf.h
> +
We've discussed about this and I agreed with you to put the bpf map structure in a common place. But I was wrong since any bpf object loaded which include this header will raise a new copy in memory of all the maps that lies inside it.

My suggestion is to maintain inside `maps.bpf.h` the common structures used for keys and values, since it could be imported by cgo directives to be used in Go source files, and let the bpf map structure initialization - SEC(".maps") - inside `map_name_bpf.h` or in the same `prog.bpf.c` for the sake of clarity.

Another possible approach (not tested by me) would be to define the bpf map structure inside the common `maps.bpf.h` and let the initialization - SEC(".maps") - happen after the header inclusion.

What do you think?

2021-10-06 12:42 UTC, geyslan requested changes
Requesting changes.

2021-10-06 18:54 UTC, chkhalt commented on KubeArmor/BPF/codegen.bpf.h
> +}
mmm, good point! I'm gonna move the code.

2021-10-08 20:27 UTC, chkhalt commented on KubeArmor/BPF/codegen.bpf.h
> +}
@geyslan, I moved the common part declaring some functions in `common.bpf.h`.
The file `shared.h` is imported in the beginning of `sharedMaps.go`, so I wasn't able to define too much things inside it (include `vmlinux.h`, for example) wihout compilation error. Thus, for now, the code in `shared.h` still the same.

What you think?

2021-10-08 20:34 UTC, chkhalt commented on KubeArmor/BPF/maps.bpf.h
> +
@geyslan, @it-with-us. I'm including some alternative logic to reuse loaded maps in the commit cebdf2661b23d8258fda5cf7814135a0a7715491, if you prefer we can make this part of another PR. What you think?

2021-10-09 11:23 UTC, geyslan commented on KubeArmor/BPF/codegen.bpf.h
> +}
LGTM.

2021-10-09 14:15 UTC, geyslan commented
I've put a test here for the dynamic (runtime) map reuse from bpf side: https://github.com/geyslan/libbpfgo/tree/main/selftest/ringbuffers-duplicate

2021-10-11 03:48 UTC, merged