add ringbuffer data structure
kubearmor/KubeArmor pull request #415
Opened 2021-10-08 07:11 UTC by Ankurk99

Signed-off-by: Ankur Kothiwal <ankur.kothiwal@accuknox.com>

2021-10-26 18:31 UTC, geyslan requested changes
Ankur, I've put some comments. Thanks.

2021-10-26 18:31 UTC, geyslan commented on KubeArmor/BPF/ringbuffer.bpf.c
> +int syscall__sys_execve(struct trace_event_raw_sched_process_exec *ctx) {
We have here a `tracepoint` instrumentation.

2021-10-26 18:31 UTC, geyslan commented on KubeArmor/eventAuditor/ringbufferMonitor.go
> +	_, err = prog.AttachKprobe("syscalls/sys_enter_execve")
And here we have a `kprobe` attachment. We've already discussed this. I assume you were testing with kprobe again and forgot to sync the bpf part. But I suggest you use `tracepoint` instrumentation whenever possible `AttachTracepoint(category, event)`.

2021-10-26 18:31 UTC, geyslan commented on KubeArmor/eventAuditor/ringbufferMonitor.go
> +	defer bpfModule.Close()
We can't close the module even with defer since the object (program and map) must continue in memory. I know that we have a infinite loop in the line 53 assuring we can stay inside the function as needed, but please remove this defer later. The bpf management can be done using ebpfManager outside of this call. :+1:

2021-10-27 05:28 UTC, Ankurk99 commented
Hey Geyslan, thank you for the feedback. Sorry but this PR is a little old and I was testing my code with all the changes you mentioned.

2021-11-02 17:18 UTC, Ankurk99 commented
Ringbuffer implementation with kubearmor reference Pull request #465

2021-11-02 17:18 UTC, closed without merging