EKS Cluster Setup Documentation
kubearmor/KubeArmor pull request #583
Opened 2022-01-30 11:04 UTC by slayer321

Signed-off-by: slayer321 <sachin.maurya7666@gmail.com>
This PR solves #493

2022-02-02 04:48 UTC, daemon1024 commented
Hey @slayer321 thanks for the PR.

As mentioned in the meta issue https://github.com/kubearmor/KubeArmor/issues/477

We wanted to use collapsible sections to include docs as part of single file to avoid redirecting users to various links. Can you update your PR to accommodate that?

More about collapsible sections https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections

2022-02-02 18:08 UTC, slayer321 commented
Hey @daemon1024, I added docs in collapsible sections. Is it what was expected?

2022-02-03 08:31 UTC, daemon1024 requested changes

2022-02-03 08:31 UTC, daemon1024 commented on getting-started/deployment_guide.md
> +</details>
Since this is part of the deployment guide already, we don't need it

2022-02-03 08:31 UTC, daemon1024 commented on getting-started/deployment_guide.md
> +
```suggestion
* <details>
  <summary><b>EKS Cluster Setu></b></summary>

```

2022-02-03 15:15 UTC, slayer321 commented
I made the changes and was trying to push it got an error
```
To https://github.com/slayer321/KubeArmor.git
 ! [rejected]        issue-493 -> issue-493 (non-fast-forward)
error: failed to push some refs to 'https://github.com/slayer321/KubeArmor.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Also did git pull
```
sachin@ubuntu:~/goworkspace/src/github/opensource/KubeArmor$ git branch 
  issue-493
* main
sachin@ubuntu:~/goworkspace/src/github/opensource/KubeArmor$ git pull
Already up to date.
```

what I can see is @nam-jaehyun  has made some changes in PR .. is it due to that

2022-02-03 16:07 UTC, daemon1024 commented
> is it due to that?
Right.
Can you do a git pull on `issue-403` branch?
You might need to do `git pull --rebase` specify remote and branch if needed.

2022-02-07 14:38 UTC, merged