Update Policy Matcher
kubearmor/KubeArmor pull request #668
Opened 2022-04-11 07:40 UTC by nam-jaehyun

- update policy matcher
- upgrade protobuf version
- update test scenarios and policies

2022-04-11 10:28 UTC, nam-jaehyun commented
Once this PR is merged, I'll raise a PR for the SELinux enforcer on top of this.

2022-04-12 03:04 UTC, nyrahul requested changes

2022-04-12 03:04 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +					if dm.Node.NodeIP == "" && timeout == 60 {
We can push this condition outside of the for loop and just check for single condition `dm.Node.NodeIP == ""`.

2022-04-12 03:04 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +		if K8s.InitK8sClient() {
We can reduce nesting if the other condition is handled ... 
```suggestion
		if !K8s.InitK8sClient() {
		       print error
		       return
		}
		// ... normal processing
		
```

2022-04-12 04:28 UTC, nam-jaehyun commented
Updated the code according to @nyrahul 's feedback.

2022-04-15 09:07 UTC, merged