added unlink, unlinkat syscalls
kubearmor/KubeArmor pull request #737
Opened 2022-06-14 05:19 UTC by rksharma95

added sycalls `unlink` and `unlinkat` to the bpf module to get logs.

2022-06-14 08:31 UTC, nyrahul commented
Thanks @rksharma95 .. Can you please attach the same telemetry events generated with unlink/unlinkat?

2022-06-14 12:02 UTC, rksharma95 commented
here are the telemetry events generated for a sequence of commands executed inside the pod monitored by kubearmor:

```
// inside pod
$ touch testFile.txt
$ rm testFile.txt
$ mkdir testDir
$ rm -r testDir 
```
telemetry events (unlink/unlinkat syscall events only)
```json
{"Timestamp":1655205972,
"UpdatedTime":"2022-06-14T11:26:12.414264Z",
"ClusterName":"default",
"HostName":"kubearmor-dev",
"NamespaceName":"multiubuntu",
"PodName":"ubuntu-1-deployment-5bd8d67678-8tgph",
"Labels":"container=ubuntu-1,group=group-1",
"ContainerID":"159c717ff7bc9f9df51ea01b9250c0e3492001ea26d2632e119f5115a3233729",
"ContainerName":"ubuntu-1-container",
"ContainerImage":"kubearmor/ubuntu-w-utils:0.1@sha256:b4693b003ed1fbf7f5ef2c8b9b3f96fd853c30e1b39549cf98bd772fbd99e260",
"ParentProcessName":"/bin/bash",
"ProcessName":"/bin/rm",
"HostPPID":8433,
"HostPID":8853,
"PPID":251,
"PID":261,
"Type":"ContainerLog",
"Source":"/bin/rm testFile.txt",
"Operation":"File",
"Resource":"testFile.txt",
"Data":"syscall=SYS_UNLINKAT fd=-100 flags=","Result":"Passed"}

{"Timestamp":1655206012,
"UpdatedTime":"2022-06-14T11:26:52.135853Z",
"ClusterName":"default",
"HostName":"kubearmor-dev",
"NamespaceName":"multiubuntu",
"PodName":"ubuntu-1-deployment-5bd8d67678-8tgph",
"Labels":"container=ubuntu-1,group=group-1",
"ContainerID":"159c717ff7bc9f9df51ea01b9250c0e3492001ea26d2632e119f5115a3233729",
"ContainerName":"ubuntu-1-container",
"ContainerImage":"kubearmor/ubuntu-w-utils:0.1@sha256:b4693b003ed1fbf7f5ef2c8b9b3f96fd853c30e1b39549cf98bd772fbd99e260",
"ParentProcessName":"/bin/bash",
"ProcessName":"/bin/rm",
"HostPPID":8433,
"HostPID":8917,
"PPID":251,
"PID":264,
"Type":"ContainerLog",
"Source":"/bin/rm -r testDir",
"Operation":"File",
"Resource":"testDir",
"Data":"syscall=SYS_UNLINKAT fd=-100 flags=AT_REMOVEDIR","Result":"Passed"}

```

2022-06-14 14:52 UTC, nyrahul commented
Why is the fd value -100 in the event details?

2022-06-16 09:29 UTC, nyrahul commented
Can you please squash the commits into a single one? Thanks

2022-06-20 16:14 UTC, nyrahul commented
@rksharma95 , can you remove the print of fd value from the event?

2022-06-20 16:15 UTC, nyrahul commented
> @rksharma95 , can you remove the print of fd value from the event?

Looks like it is already removed. The telemetry events are based on old code I guess!

2022-06-20 16:34 UTC, rksharma95 commented
> > @rksharma95 , can you remove the print of fd value from the event?
> 
> Looks like it is already removed. The telemetry events are based on old code I guess!

yes, the `fd` value has been removed.

2022-06-27 03:39 UTC, rksharma95 commented
> Why is the fd value -100 in the event details?

it's a special value of `fd`, fd=-100 or `AT_FDCWD` states that pathname should be interpreted relative to the current working directory of the calling process.

2022-07-28 10:37 UTC, nyrahul requested changes

2022-07-28 10:37 UTC, nyrahul commented on KubeArmor/BPF/system_monitor.c
> +    struct dentry *dentry = (struct dentry*) PT_REGS_PARM2(ctx);
```suggestion
    struct path *dir = (struct path*) PT_REGS_PARM1(ctx);
    struct dentry *dentry = (struct dentry*) PT_REGS_PARM2(ctx);
```

2022-07-28 10:37 UTC, nyrahul commented on KubeArmor/BPF/system_monitor.c
> +    p.dentry = READ_KERN(dentry);
We should have a sanity null checks for the returned pointers `dir` and `dentry`?

2022-07-29 17:27 UTC, nyrahul commented
@achrefbensaad , this needs conflict resolution. Thanks

2022-07-29 18:31 UTC, achrefbensaad commented on KubeArmor/BPF/system_monitor.c
> +    p.dentry = READ_KERN(dentry);
Done

2022-08-01 04:48 UTC, nyrahul approved these changes
LGTM. Thank you for handlling all the changes at top speed.

2022-08-01 04:48 UTC, merged