get all required data for karmor probe when kubearmor is running
kubearmor/KubeArmor pull request #774
Opened 2022-07-18 09:42 UTC by Essietom

Signed-off-by: essietom <essietom@gmail.com>

2022-08-02 02:41 UTC, nyrahul requested changes

2022-08-02 02:41 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +func KarmorDataToFile(val KarmorData, destFile string) {
this function should go in `karmorprobedata.go` file.

2022-08-02 02:41 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +		log.Println(err)
return in case of this failure.

2022-08-02 02:41 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +			fmt.Fprintf(os.Stderr, "Failed to create a file (%s, %s)\n", destFile, err.Error())
Why are we using `fmt` in someplaces and `log` in other cases?

2022-08-02 02:41 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +		fmt.Fprintf(os.Stderr, "Failed to open a file (%s, %s)\n", destFile, err.Error())
return in case of failure.

2022-08-02 02:41 UTC, nyrahul commented on KubeArmor/core/kubeArmor.go
> +func KarmorDataToFile(val KarmorData, destFile string) {
I think this whole function can be reduced to couple of lines. Something like this:

```go
j, err := json.Marshal(val)
// failure handling
err := ioutil.WriteFile(destFile, j, 0644)
// failure handlling
```

Why use `os.Stat()`, `os.Create()`, `os.Close()` etc?

2022-08-03 09:35 UTC, nyrahul commented
As discussed on call, please handle:
- [ ] squash the commits
- [ ] resolve conflicts
- [ ] license headers .. change to 2022

2022-08-03 10:13 UTC, daemon1024 commented on KubeArmor/core/karmorprobedata.go
> +	"io/ioutil"
Please refer https://go.dev/doc/go1.16#ioutil for switching ioutil to suggested APIs.

2022-08-15 14:49 UTC, closed without merging