add FAQs
kubearmor/KubeArmor pull request #786
Opened 2022-07-28 12:47 UTC by Ankurk99

ref #647

2022-07-31 05:25 UTC, nyrahul commented on getting-started/FAQ.md
> +KubeArmor, apart from been a policy enforcement engine also emits pod/container visibility data. It uses an eBPF-based system monitor which keeps track of process life cycles in containers and even n
Please remove ref to Accuknox. We can just call it Discovery-Engine.

2022-07-31 05:25 UTC, nyrahul commented on getting-started/FAQ.md
> +   * Security Profile updates are manual and difficult
This needs serious overhaul.

2022-08-09 03:05 UTC, seswarrajan approved these changes
LGTM

2022-08-09 09:02 UTC, achrefbensaad approved these changes

2022-08-09 11:32 UTC, nyrahul requested changes

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +  * All the operating systems doesn't supports the LSMs consistently
```suggestion
  * All the OS distributions do not support the LSMs consistently. For e.g, [GKE COS](https://cloud.google.com/container-optimized-os/) supports AppArmor while [Bottlerocket](https://aws.amazon.com/bottlerocket/) supports SELinux and BPF-LSM.
```

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +  * It requires knowledge of all of these security context
```suggestion
  * The Pod Security Context expect the security profile to be specified in its native language, for instance, apparmor profile if AppArmor is to be used, SELinux profile if SELinux is to be used. The profile language is extremely complex and this complexity could backfire i.e, it could lead to security holes.
```

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +  * It maps YAML rules to LSMs (apparmor, bpf-lsm) rules so prior knowledge of different security context is not required.
```suggestion
  * It maps YAML rules to LSMs (apparmor, bpf-lsm) rules so prior knowledge of different security context (native apparmor, SELinux) is not required.  
```

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +  * KubeArmor also runs in systemd mode so can directly run and protect Virtual Machines or Bare-metal machines too.
```suggestion
  * KubeArmor also runs in systemd mode so can directly run and protect Virtual Machines or Bare-metal machines too.  
  * Pod Security Context cannot leverage BPF-LSM at all today. BPF-LSM provides more programmatic control over the policy rules.
  * Pod Security Context do not manage abstractions. As an example, you might have two nodes with Ubuntu, two nodes with Bottlerocket. Ubuntu, by default has apparmor and Bottlerocket has BPF-LSM and SELinux. Kubearmor internally picks the right primitives to use for enforcement and the user does not have to bother explicitly stating what to use.
```

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +KubeArmor avoids these loopholes by using inline mitigation using LSMs. With LSMs the controls are applied even before the process is spawned thus reduces the attack surface in the first place.
```suggestion
KubeArmor avoids these loopholes by using inline mitigation using LSMs. With LSMs the controls are applied even before the process is spawned thus reducing the attack surface in the first place.
```

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +```{
```suggestion
```json
{
```

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +  Kubernetes admission controllers are set of extensions that acts as a gatekeeper and help govern and control Kubernetes clusters. They intercepts requests to the Kubernetes API server prior to the
```suggestion
  Kubernetes admission controllers are set of extensions that acts as a gatekeeper and help govern and control Kubernetes clusters. They intercept requests to the Kubernetes API server prior to the persistence of the object into etcd.  
```

2022-08-09 11:32 UTC, nyrahul commented on getting-started/FAQ.md
> +  KuberArmor has a lead here. It runs as a daemonset and restricts the behavior of containers at the system level. KubeArmor allows operators to define security policies based on K8s metadata and sim
```suggestion
  KuberArmor protects the pods from within. It runs as a daemonset and restricts the behavior of containers at the system level. KubeArmor allows one to define security policies for the assets/resources (such as files, processes, volumes etc) within the pod/container, select those based on K8s metadata and apply these security policies at runtime.
```

2022-08-09 12:40 UTC, Ankurk99 commented
Thank you @nyrahul for the in-depth review

2022-08-28 16:55 UTC, nyrahul approved these changes
LGTM 👍🏼

2022-08-28 16:56 UTC, merged