added tag to hsp to make it cluster-scoped resource
kubearmor/KubeArmor pull request #807
Opened 2022-08-10 12:59 UTC by rksharma95

`KubeArmorHostPolicy` is not a namespace scoped resource, therefore marked the type `KubeArmorHostPolicy` with tag `+genclient:nonNamespaced`.

Managing `hsp` with client-go API was an issue earlier. This PR fixes that issue.

Signed-off-by: rk <ramakant@accuknox.com>

2022-08-10 13:21 UTC, nyrahul approved these changes

2022-08-10 14:26 UTC, achrefbensaad approved these changes
LGTM

2022-08-11 04:38 UTC, nam-jaehyun commented
don't we need to also change Makefile?

2022-08-11 04:41 UTC, nam-jaehyun commented
also, you upgrade the version of kubebuilder for hsp.
then, it would be better to upgrade the version of kubebuilder for ksp too.

2022-08-11 05:49 UTC, rksharma95 commented
> don't we need to also change Makefile?

@nam-jaehyun what are the changes to be expected in the Makefile?

2022-08-11 06:25 UTC, nam-jaehyun commented
> > don't we need to also change Makefile?
> 
> @nam-jaehyun what are the changes to be expected in the Makefile?

removing the out-dated line in Makefile

https://github.com/kubearmor/KubeArmor/blob/64635aca1105ab85ea63cd167e85cee21cbfcf20/pkg/KubeArmorHostPolicy/Makefile#L54

2022-08-11 15:11 UTC, nam-jaehyun requested changes
Let's merge it after updating Makefile.

2022-08-12 10:46 UTC, merged