go vulnerability scan
kubearmor/KubeArmor pull request #899
Opened 2022-09-17 22:05 UTC by sheharyaar

Initial work on #889
Signed-off-by: Mohammad Shehar Yaar Tausif <sheharyaar48@gmail.com>

2022-09-17 22:06 UTC, sheharyaar commented
Is the changes to makefile sufficient? After makefile, I will make changes to GH actions

2022-09-18 03:34 UTC, kranurag7 reviewed
@sheharyaar Please look at the comment https://github.com/kubearmor/KubeArmor/issues/889#issuecomment-1250183369

2022-09-18 08:36 UTC, sheharyaar commented
Made the changes to Makefile

2022-09-19 18:39 UTC, sheharyaar commented
@kranurag7 any more changes required in the Makefile?

2022-10-18 14:05 UTC, kranurag7 requested changes
@sheharyaar Sorry for late response. Instead of making changes in Makefile, you can change implement the same in GitHub actions in [ci-test-go](https://github.com/kubearmor/KubeArmor/blob/main/.github/workflows/ci-test-go.yml). Please check this for [reference](https://github.com/caarlos0/meta/blob/main/.github/workflows/govulncheck.yml).

2022-11-02 03:40 UTC, nyrahul commented
@sheharyaar , any updates on this?

One question, after running `make scan` with the PRs updated Makefile, do you see any issues reported that needs to be handled? Or is the report clean?

2022-11-02 05:39 UTC, sheharyaar commented
The report was clean after running make scan. I will update the PR as suggested by kanurag7.

2022-11-02 09:29 UTC, sheharyaar commented
@nyrahul after running govulncheck today, I got multiple informational vulnerabilities. Should I create a new Issue or just send them here.

2022-11-02 10:18 UTC, sheharyaar commented
Placing govulncheck in ci-test-go would cause action to fail even on informational vulnerabilities.

2022-11-02 14:46 UTC, nyrahul commented
> Placing govulncheck in ci-test-go would cause action to fail even on informational vulnerabilities.

Can you attach the `make scan` report here in the issue?

2022-11-02 15:41 UTC, sheharyaar commented
Attached to the following link : [govulnscan.log](https://github.com/kubearmor/KubeArmor/files/9921926/govulnscan.log)

```
go install golang.org/x/vuln/cmd/govulncheck@latest ;\
cd /home/wazir/workspace/playground/temp/KubeArmor/KubeArmor;\
govulncheck -v ./... ;\
cd /home/wazir/workspace/playground/temp/KubeArmor/KubeArmor/BPF/tests;\
govulncheck -v ./... ;\
cd /home/wazir/workspace/playground/temp/KubeArmor/KubeArmor/../deployments;\
govulncheck -v ./... ;\
cd /home/wazir/workspace/playground/temp/KubeArmor/KubeArmor/../pkg/KubeArmorAnnotation ;\
govulncheck -v ./... ;\
cd /home/wazir/workspace/playground/temp/KubeArmor/KubeArmor/../pkg/KubeArmorController ;\
govulncheck -v ./... ;\
cd /home/wazir/workspace/playground/temp/KubeArmor/KubeArmor/../pkg/KubeArmorHostPolicy ;\
govulncheck -v ./... ;\
cd /home/wazir/workspace/playground/temp/KubeArmor/KubeArmor/../pkg/KubeArmorPolicy ;\
govulncheck -v ./... ;\

govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.

Scanning for dependencies with known vulnerabilities...
Found 2 known vulnerabilities.

Vulnerability #1: GO-2022-1095
  Due to unsanitized NUL values, attackers may be able to
  maliciously set environment variables on Windows. In
  syscall.StartProcess and os/exec.Cmd, invalid environment
  variable values containing NUL values are not properly checked
  for. A malicious environment variable value can exploit this
  behavior to set a value for a different environment variable.
  For example, the environment variable string "A=B\x00C=D" sets
  the variables "A=B" and "C=D".

  Call stacks in your code:
      #1: for function Cmd.CombinedOutput
        github.com/kubearmor/KubeArmor/KubeArmor/common.GetCommandOutputWithoutErr
            common/common.go:257:32
        os/exec.Cmd.CombinedOutput
      #2: for function Cmd.Run
        github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmorDaemon.WatchDefaultPosture
            core/kubeUpdate.go:2475:2
        k8s.io/client-go/informers.sharedInformerFactory.Start
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/informers/factory.go:134:4
        k8s.io/client-go/tools/cache.sharedIndexInformer.Run
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/shared_informer.go:443:18
        k8s.io/client-go/tools/cache.controller.Run
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/controller.go:155:12
        k8s.io/apimachinery/pkg/util/wait.Until
            /home/wazir/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:92:13
        k8s.io/apimachinery/pkg/util/wait.JitterUntil
            /home/wazir/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:135:14
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil
            /home/wazir/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:158:4
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil$1
            /home/wazir/go/pkg/mod/k8s.io/apimachinery@v0.25.0/pkg/util/wait/wait.go:157:5
        k8s.io/client-go/transport.dynamicClientCert.runWorker
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/transport/cert_rotation.go:151:27
        k8s.io/client-go/transport.dynamicClientCert.processNextWorkItem
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/transport/cert_rotation.go:162:28
        k8s.io/client-go/transport.dynamicClientCert.loadClientCert
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/transport/cert_rotation.go:65:23
        k8s.io/client-go/transport.TLSConfigFor$1
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/transport/transport.go:119:31
        k8s.io/client-go/plugin/pkg/client/auth/exec.Authenticator.cert
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/plugin/pkg/client/auth/exec/exec.go:364:26
        k8s.io/client-go/plugin/pkg/client/auth/exec.Authenticator.getCreds
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/plugin/pkg/client/auth/exec/exec.go:379:32
        k8s.io/client-go/plugin/pkg/client/auth/exec.Authenticator.refreshCredsLocked
            /home/wazir/go/pkg/mod/k8s.io/client-go@v0.25.0/plugin/pkg/client/auth/exec/exec.go:435:15
        os/exec.Cmd.Run
      #3: for function Cmd.Start
        github.com/kubearmor/KubeArmor/KubeArmor/common.RunCommandAndWaitWithErr
            common/common.go:269:21
        os/exec.Cmd.Start
          There are 526 more call stacks available.
      To see all of them, pass the -json flags.

  Found in: os/exec@go1.19
  Fixed in: os/exec@go1.19.3
  More info: https://pkg.go.dev/vuln/GO-2022-1095

Vulnerability #2: GO-2022-1039
  Programs which compile regular expressions from untrusted
  sources may be vulnerable to memory exhaustion or denial of
  service. The parsed regexp representation is linear in the size
  of the input, but in some cases the constant factor can be as
  high as 40,000, making relatively small regexps consume much
  larger amounts of memory. After fix, each regexp being parsed is
  limited to a 256 MB memory footprint. Regular expressions whose
  representation would use more space than that are rejected.
  Normal use of regular expressions is unaffected.

  Call stacks in your code:
      #1: for function Parse
        github.com/kubearmor/KubeArmor/KubeArmor/feeder.Feeder.UpdateHostSecurityPolicies
            feeder/policyMatcher.go:637:37
        regexp.Compile
            /usr/local/go/src/regexp/regexp.go:137:16
        regexp.compile
            /usr/local/go/src/regexp/regexp.go:174:25
        regexp/syntax.Parse
          There are 413 more call stacks available.
      To see all of them, pass the -json flags.

  Found in: regexp/syntax@go1.19
  Fixed in: regexp/syntax@go1.19.2
  More info: https://pkg.go.dev/vuln/GO-2022-1039

Vulnerability #3: GO-2022-1095
  Due to unsanitized NUL values, attackers may be able to
  maliciously set environment variables on Windows. In
  syscall.StartProcess and os/exec.Cmd, invalid environment
  variable values containing NUL values are not properly checked
  for. A malicious environment variable value can exploit this
  behavior to set a value for a different environment variable.
  For example, the environment variable string "A=B\x00C=D" sets
  the variables "A=B" and "C=D".

  Call stacks in your code:
      #1: for function StartProcess
        github.com/kubearmor/KubeArmor/KubeArmor/common.RunCommandAndWaitWithErr
            common/common.go:269:21
        os/exec.Cmd.Start
            /usr/local/go/src/os/exec/exec.go:524:34
        os.StartProcess
            /usr/local/go/src/os/exec.go:109:21
        os.startProcess
            /usr/local/go/src/os/exec_posix.go:54:35
        syscall.StartProcess
          There are 246 more call stacks available.
      To see all of them, pass the -json flags.

  Found in: syscall@go1.19
  Fixed in: syscall@go1.19.3
  More info: https://pkg.go.dev/vuln/GO-2022-1095

=== Informational ===

The vulnerabilities below are in packages that you import, but your code
doesn't appear to call any vulnerable functions. You may not need to take any
action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2022-1038
  Requests forwarded by ReverseProxy include the raw query parameters from the inbound request, including unparseable parameters rejected by net/http. This could permit query parameter smuggling when a Go proxy forwards a parameter with an unparseable value.

  After fix, ReverseProxy sanitizes the query parameters in the forwarded query when the outbound request's Form field is set after the ReverseProxy. Director function returns, indicating that the proxy has parsed the query parameters. Proxies which do not parse query parameters continue to forward the original query parameters unchanged.
  Found in: net/http/httputil@go1.19
  Fixed in: net/http/httputil@go1.19.2
  More info: https://pkg.go.dev/vuln/GO-2022-1038

Vulnerability #2: GO-2022-0988
  JoinPath and URL.JoinPath do not remo [...]

2022-11-02 16:58 UTC, nyrahul commented
Thanks.
I see that there are 2 vulnerabilities reported directly in the kubearmor code and I believe these should be easily fixable and should be fixed in this PR.
Other informational vulnerabilities are in the deps.

2022-11-02 17:36 UTC, sheharyaar commented
Sure, I will do the required in this PR.Should I move the scan to `ci-test-go` or let it be in the Makefile. As any informational vulnerabilities in the deps too would cause the build to fail.

2022-11-04 20:51 UTC, sheharyaar commented
@nyrahul , the scan report I sent was for go 1.19. My bad for noticing it earlier. The informational vulnerabilities which have been reported have been already backported to golang packagges. I attach the report from `golang:1.18.8-bullseye` docker image. Current version of Kuberarmor does not have any vulnerable functions that are being called.

[govulnscan.log](https://github.com/kubearmor/KubeArmor/files/9941875/govulnscan.log)

2022-11-04 20:56 UTC, sheharyaar commented
I quote the documentation : 
> Govulncheck only reports vulnerabilities that apply to the current Go version. For example, a standard library vulnerability that only applies for Go 1.18 will not be reported if the current Go version is 1.19. See https://go.dev/issue/54841 for updates to this limitation.

2023-02-09 12:26 UTC, nyrahul commented
Verified that there are no vulnerabilities reported by govulncheck if the golang version >=1.19.4 is used.

I am merging these changes since manual verification using `make scan` is possible with this PR. Let's handle GH action check in a separate PR.

2023-02-09 12:26 UTC, nyrahul approved these changes
LGTM

2023-02-09 13:42 UTC, sheharyaar commented
Thanks for approving the PR. I am glad to be able to contribute to the project :)

2023-02-09 14:28 UTC, kranurag7 approved these changes
LGTM @sheharyaar, Can you also do the same for [kubearmor-client](https://github.com/kubearmor/kubearmor-client) repo?

2023-02-09 15:24 UTC, sheharyaar commented
Sure, I will create a PR there with the changes

2023-02-09 15:47 UTC, sheharyaar commented
Done. PR at https://github.com/kubearmor/kubearmor-client/pull/262/files

2023-03-09 15:07 UTC, merged