use k8s resource limits
kubearmor/KubeArmor pull request #934
Opened 2022-10-12 17:42 UTC by rksharma95

ref: #923 
Signed-off-by: rksharma95 <ramakant@accuknox.com>

2022-10-19 12:52 UTC, nyrahul approved these changes
LGTM 👍

2022-10-20 04:04 UTC, Ankurk99 requested changes
Hey @rksharma95, Can you rebase the code, it currently contains changes from other PR

2022-10-20 04:06 UTC, Ankurk99 commented on deployments/AKS/kubearmor.yaml
> +            memory: 512Mi
A question - @achrefbensaad mentioned that it will be a waste of resource to use 4 CPUs while requesting 100m, have we verified using lesser CPU?

2022-11-10 04:47 UTC, Ankurk99 commented
@rksharma95 Please remove the part containing the capability changes

2025-06-17 07:04 UTC, closed without merging